### ISSUE TITLE
py.test integration

### ISSUE THREAD

**Issue by sh3llsh0ck** [philpep/testinfra#1]
I would like to thank you for this great tool, i just saw it today and i am really impressed.

I have a question which i couldn't found it in the documentation. currently i have a py.test script and i would like to have a testinfra functionality inside my current script, for example:

I have added package is installed and service is running/enabled to my script, but when i run my script with py.test:
1-  it couldn't found Service or Package.
2- Also i noticed that testinfra doesn't show in plugins section when i run the test.
3- I have a custom pytest.ini so i can add a custom option to use it when i run py.test , which is not working with testinfra

so if i could use testinfra as a plugin so i can make use of its functionality like saltstack integration and also use all the current custom options i have at py.test it would be nice.

**Comment by philpep** [comment]
Hi, thanks for your feedback !

Testinfra doesn't expose himself as a py.test plugin, this was removed in 7d44a31c0a8db83757cf09a941193b90561742d0 maybe for bad reasons, I'll reconsider this.

But you can enable testinfra within py.test with:

`py.test -p testinfra.plugin`

**Comment by sh3llsh0ck** [comment]
Thanks!
