### ISSUE TITLE
Add support for checking crypted passwords

### ISSUE THREAD

**Issue by tongpu** [philpep/testinfra#101]
I created #100 to allow for checking crypted user passwords. Currently it's a simple extension of the User module. Should this be extended to a full Shadow module that would also allow to check for all the other possible values in `/etc/shadow`, e.g. account and password expiration?

**Comment by philpep** [comment]
Hi, I merged #100 

What we could do is to add a classmethod on `User` that return the list of all users (as user instances) and add a property for password expiration

**Comment by philpep** [comment]
Fixed in #106 (released in 1.3.0)
