### ISSUE TITLE
Execute python code remotely

### ISSUE THREAD

**Issue by retr0h** [philpep/testinfra#104]
Currently have the following test:

```
def test_vnc_console_response(Command, Ansible):
    domain = Ansible('debug', "msg={{ ansible_domain }}")['msg']
    cmd = 'curl -IL https://api.pub.{}:6080/vnc_auto.html'.format(domain)
    out = Command.check_output(cmd)

    assert re.search(r'HTTP/1.1 200 OK', out)
```

Am looking to convert it to python-requests:

```
def test_vnc_console_response(Ansible):
    domain = Ansible('debug', "msg={{ ansible_domain }}")['msg']
    url = 'https://api.pub.{}:6080/vnc_auto.html'.format(domain)
    r = requests.get(url)

    assert r.ok
```

However, the latter will run from the host executing testinfra, and not on the remote host.  Is there a way to execute python code on the remote host.  Reason being, the URL is not available to the system executing the test.

**Comment by philpep** [comment]
Yes test are run in the system executing the tests (so with local connection or ansible + local this work).

Executing portion of python code or whole test remotely could be amazing to code ;)

**Comment by pporada-gl** [comment]
Wouldn't an alternative be to deploy your code to the remote server and run your curl/python-requests as a post deploy test?

**Comment by emayssat-ms** [comment]
@pporada-gl Yes, I am doing exactly this. The convenience of such functionality would be to have your test self contained (in the testinfra code). One issue though may be readability. How do I know that the code I am reading is executing remotely or locally? Oh, well....

**Comment by m4h3** [comment]
readability could be done with python decorators
