### ISSUE TITLE
openSuse Leap 42 - testinfra not detecting valid package manager

### ISSUE THREAD

**Issue by marcinpraczko** [philpep/testinfra#107]
Hi,

Would like to discuss improvements related with detecting valid system. I am running OpenSUSE Leap 42.1. 
Test infra has been installed from pip and seems be working well except is not detecting what is valid package manager. Tried find this in documentation however was not able to find anything which helped me. 

**Details:**
```python
def test_package_git(Package):
    pkg = Package("git")
    assert pkg.is_installed == True
```
**When running testinfra, following error is displayed:**
```bash
    @property
    def is_installed(self):
        out = self.check_output("dpkg-query -f '${Status}' -W %s" % (
>           self.name,)).split()
E       Failed: Unexpected exit code 127 for CommandResult(command=b"dpkg-query -f '${Status}' -W git", exit_status=127, stdout=b'', stderr=b'/bin/sh: dpkg-query: command not found\n')
```

From my understanding testinfra is running dpkg-query instead of rpm command.

**Questions and actions:**
1. Is there any way which I can force which package management should be used?
2. How I can contribute to help with this. My python skills are increasing - however are not on level yet that I can add patch for testinfra. Some hints to developers guidelines are welcome. 
3. Maybe will be worth to display info (when verbose) what system has been detected?

System
```bash
Welcome to openSUSE Leap 42.1 - Kernel \r (\l).
```

**Result form testinfra**
```bash
platform linux -- Python 3.4.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python3
cachedir: .cache
rootdir: /home/haclet/myworkspace/test_testinfra, inifile:
plugins: testinfra-1.3.0
collected 2 items

test_myinfra.py::test_passwd_file[local] PASSED
test_myinfra.py::test_package_git[local] FAILED
```

Please advice.

**Comment by philpep** [comment]
Hi, thanks for the report.

The package manager detection occur in https://github.com/philpep/testinfra/blob/master/testinfra/modules/package.py#L56

Basically It seems that you have a ``apt-get`` command and testinfra thinks the package manager is APT.

This must be fixed, maybe by trying to add an "os family" value in SystemInfo module (debian or redhat).

1)  I think it's a good idea to provide AptPackage, YumPackage and a Package (that does the detection).
2) See https://github.com/philpep/testinfra/blob/master/CONTRIBUTING.rst for contributing and testing (you might need some docker knowledge), you can skip the ``tox`` part, basically this is how I develop on testinfra:

```
git clone git://github.com/philpep/testinfra
cd testinfra
virtualenv .local
source .local/bin/activate
python setup.py develop
py.test testinfra
```
(The first time you run the tests, this will build docker images and can take some time).

3)
```
logger = logging.getLogger("testinfra")
logger.info("hi")
```
should display "hi" when testinfra (py.test) is in verbose mode.

**Comment by marcinpraczko** [comment]
Hi,

> Basically It seems that you have a apt-get command and testinfra thinks the package manager is APT

This is quite surprise but you were right. Thank you instructions in terms of contributing and how to run test. Started working on this and - analysing code and see that `apt-get` command is checked before `rpm`. Not sure why have this on OpenSUSE installed. Trying sort this, ansible is detecting systems quite well (also added small fix there). Let me check what I can to do.

**Comment by marcinpraczko** [comment]
Hi @philpep 

Created initial branch which may help with this a bit better. As I mentioned my python skills are limited so far - but learning quickly.

Before I will create PR, we can create something which may work.
First: all dockers tests failed on my OpenSuse - and have to investigate why - as I can see there is missing paramiko package. Need a bit more time.
Second: my initial branch have quick / dirty fix for openSUSE, but seems be working very well so far.

- https://github.com/marcinpraczko/testinfra/commit/f7f34cdc8553c2fa7d5636987ad4018447c6ce77

Result:
```bash
plugins: testinfra-1.3.0
collected 1 items

t01.py .
```

No errors and `t01.py`:
```python
def test_package_git(Package):
    pkg = Package("git")
    assert pkg.is_installed == True
```

Tried find documentation about others distribution what string is returning - have not luck so far. Will work on this later as well.
Hope that helps.

**Comment by philpep** [comment]
Hi, thanks. I added my comments on your commit marcinpraczko@294d64a

**Comment by marcinpraczko** [comment]
Hi, I see that this is updated now and seems be working on my OpenSuse automatically.

However I also done research how ansible is doing this and this is what I found:
- For detecting platform: ansible is using `platform` module as well:
https://github.com/ansible/ansible/blob/1b29c879362cc528e82c151a8ff61da2ae955b79/lib/ansible/module_utils/facts.py#L669-L675

- Then for detecting distribution version or release ansible is using predefined files:
https://github.com/ansible/ansible/blob/1b29c879362cc528e82c151a8ff61da2ae955b79/lib/ansible/module_utils/facts.py#L622

So as summary:
- This patch which was applied here allowed fix problem on OpenSuse Leap 42 (now testinfra is working well)
- However I am suggesting that this should be implemented differently to help avoid similar situations in the feature and as I can see code from ansible can be usable.

Hope that helps.

**Comment by marcinpraczko** [comment]
Would like to also ask here - whether there is a way to display variables which testinfra is using for host. For example during debug (like this issue) have some option to display vars for host?

Example:
```bash
testinfra --some-option test.py

# Result:
host01 - has following variables
system: Debian
release: 4.0
```

Do you think that this is hard to implement - or is already in code - if yes - how I can get access to it?

**Comment by marcinpraczko** [comment]
And I am happy to work on branch for this distro detection. As mentioned - can write basic code - which probably need to be reviewed and refactored to match testinfra coding standard.

**Comment by philpep** [comment]
I close this issue. Feel free to reopen if you have new comments (or PR) to add regarding this issue.
