### ISSUE TITLE
Terraform Support Planned?

### ISSUE THREAD

**Issue by beginrescueend** [philpep/testinfra#108]
I see the TestInfra supports Ansible, Salt, Puppet/Facter, and Chef.

Do you have any plans to add Terraform to the mix? https://www.terraform.io/

Thanks!

**Comment by philpep** [comment]
Hi, I known nothing about terraform, but if it has a API (even cli based) it can be implemented as modules. An if it can provide a way to run arbitrary commands on remote hosts, it can be implemented as a connection backend too.
