### ISSUE TITLE
File.contains behavior

### ISSUE THREAD

**Issue by alop** [philpep/testinfra#114]
I recently wrote a test to check grub.cfg for serial console settings. The test looks like
```
def test_grub(File):
    grub = File('/boot/grub2/grub.cfg')

    assert grub.contains('console=tty0')
    assert grub.contains('vga=normal')
    assert grub.contains('consoleblank=0')
    assert grub.contains('nofb')
    assert grub.contains('nomodeset')
    assert grub.contains('video=vesafb:off')
    assert grub.contains('gfxpayload=text')
    assert grub.contains('text')
```
I can't understand how this is failing
```
File = <class 'testinfra.modules.base.GNUFile'>

    def test_grub(File):
        grub = File('/boot/grub2/grub.cfg')
    
>       assert grub.contains('console=tty0')
E       assert <bound method GNUFile.contains of <file /boot/grub2/grub.cfg>>('console=tty0')
E        +  where <bound method GNUFile.contains of <file /boot/grub2/grub.cfg>> = <file /boot/grub2/grub.cfg>.contains

tests/test_default.py:52: AssertionError
```

I looked at the code, looks like it's just grep, which is passing on the command line
```
[root@mhv1 ~]# grep -qs -- console=tty0 /boot/grub2/grub.cfg 
[root@mhv1 ~]# echo $?
0
[root@mhv1 ~]# 
```

I *am* running with sudo

The actual match looks like
```
grep console=tty0 /boot/grub2/grub.cfg 
	linux16 /vmlinuz-3.10.0-327.el7.x86_64 root=/dev/mapper/rhel-root ro crashkernel=auto rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet net.ifnames=0 biosdevname=0 console=tty0 vga=normal consoleblank=0 nofb nomodeset video=vesafb:off gfxpayload=text text
	linux16 /vmlinuz-0-rescue-ba64f73a96244ba0a0ce1673be601765 root=/dev/mapper/rhel-root ro crashkernel=auto rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet net.ifnames=0 biosdevname=0 console=tty0 vga=normal consoleblank=0 nofb nomodeset video=vesafb:off gfxpayload=text text
```

**Comment by philpep** [comment]
Hi,

To see what command is actually run, run testinfra with ``-vvs``. You will see the full command (including sudo) and return code, stdout / stderr.

Btw, to speedup this test you can use the ``content`` attribute to get the entire file, still reasonable while it's not a huge file.

```python
def test_grub(File):
    content = File('/boot/grub2/grub.cfg').content
    assert b'console=tty0' in content
    # ...
```

**Comment by alop** [comment]
thanks, that pattern is faster and 'just works'

**Comment by philpep** [comment]
So did you catch an issue or bug with sudo and `contains()` ?

**Comment by alop** [comment]
No, I realized the example you provided was much faster, so I didn't dig into it further.

**Comment by corbyshaner** [comment]
This trick also works for cases where you're searching for content that has quotes in it.
If you have `LogFormat "%t %{X-Forwarded-For}i %l %u \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \"%D\" \"%T\" combined` in an Apache config, this code will match it:
`def test_ssl_conf_custom(host):
    conf = host.file('/etc/httpd/conf.d/ssl.conf').content
    assert b'LogFormat "%t %{X-Forwarded-For}i %l %u \\"%r\\" %>s %b \\"%{Referer}i\\" \\"%{User-Agent}i\\" \\"%D\\" \\"%T\\" combined' in conf`
