### ISSUE TITLE
How to get target OS type in Testinfra when running a test remotely?

### ISSUE THREAD

**Issue by techraf** [philpep/testinfra#118]
I run the following Testinfra test using Paramiko connection:

```
host$ testinfra -v --host=target test.py
```

The test is supposed to check for the target system OS. If I use the following method, `local://` refers to the `host` machine not the `target`.

Given that I don't want to hardcode the connection string in the test itself, how can I get the value of `os` on `target` machine?

```
import testinfra

os = testinfra.get_backend(
  "local://"
).get_module("SystemInfo").type

def test_passwd_file(File):
    passwd = File("/etc/passwd")
    if os == "darwin":
        assert passwd.group == "wheel"
    if os != "darwin":
        assert passwd.group == "root"
```

**Comment by philpep** [comment]
All testinfra [modules](https://testinfra.readthedocs.io/en/latest/modules.html) can be used as pytest fixtures.

```python
def test_passwd_file(File, SystemInfo):
    if SystemInfo.type == "darwin":
        [....]
```

Please be aware that darwin support is not fully implemented for now.
