### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by philpep** [philpep/testinfra#12]
We have some basic test that can run in travis. But we also have integration test that can run using docker and vagrant inside popular OS like debian, ubuntu, fedora, centos.

Theses tests can be easily run from the developper side (just need vagrant and docker), and my jenkins instance can run theses tests as well: https://jenkins.philpep.org/job/testinfra/

We need to write more of theses integration tests, test more backends and document the test procedure.

**Comment by daenney** [comment]
We can actually run these on Travis as well since you can spin up Docker on your Travis host. It becomes a bit of Dockerception though.  CircleCI supports that too.
