### ISSUE TITLE
Test scene provisioning

### ISSUE THREAD

**Issue by maratsh** [philpep/testinfra#122]
I can not understand how to run tests before provisioning. I see only the tests already working installations.

**Comment by philpep** [comment]
Hi, I'm not sure to understand your question. Testinfra is just a test framework for writting tests, It don't run and or provision systems. It rely to you to decide how and when run your tests.

**Comment by maratsh** [comment]
In  example, test-kitchen contain provisioners, that can provision platforms for running tests.

Do I understand correctly that this is not and I have to do this stage myself?

**Comment by philpep** [comment]
Yes, testinfra isn't a provisioner neither a VM management tool, but you can write your own code to provision after/before/during your test using setup/teardown functions.

Or use other tools for that like vagrant, test-kitchen that you mentioned etc.

If you want to test ansible code, take a look at https://github.com/metacloud/molecule that run VMs/provision and run test (à la test-kitchen) it has a smooth integration with testinfra.

**Comment by maratsh** [comment]
Thank you! I need something like that for saltstack

**Comment by philpep** [comment]
Ok, some useful links for salt:

https://medium.com/@syndicut/testing-salt-formulas-with-test-kitchen-and-testinfra-d2b8642e6a39 (using test kitchen)
https://www.logilab.org/blogentry/7159812 and https://www.logilab.org/blogentry/7159938 (python scripts and docker)

You should also consider vagrant, it's a great tool.
