### ISSUE TITLE
Socket: add backend based on ss

### ISSUE THREAD

**Issue by philpep** [philpep/testinfra#124]
On docker images netstat is usually not installed but ss (from iproute2) is.

Related to #123

**Comment by giovtorres** [comment]
For this issue, I was curious if your plan was to swap `netstat` for `ss`?  I find that the centos:7 and centos:6 docker images have neither the net-tools or iproute packages installed.  So I end up having to install net-tools for socket tests in those environments.

The centos/7 vagrant box does come with iproute pre-installed, but not net-tools.

**Comment by philpep** [comment]
@giovtorres this issue was originally for debian image which has ss but no netstat. Given what you say on centos I think we could support both (netstat and ss).

**Comment by tonyganga** [comment]
+1 

I just ran into this on CentOS 7 (CentOS Linux release 7.4.1708)

Have to install net-tools in order to run any tests that call sockets, and this is unfortunate because netstat is deprecated in favor of the iproute2 tool `ss`. Do you want to retain both netstat and ss, or deprecate netstat entirely? @philpep

**Comment by spul** [comment]
+1

I'd rather call this a bug. From man netstat:

```
NOTES
       This  program  is  mostly obsolete.  Replacement for netstat is ss.  Replacement for netstat -r is ip route.  Replacement for
       netstat -i is ip -s link.  Replacement for netstat -g is ip maddr.
```

Recent versions of Linux distributions do not ship netstat by default and use ss instead.

**Comment by gvz** [comment]
just saw you have the socket-ss branch that should fix this issue.
Is there any thing missing in that branch or iis it about to be merged into the master branch?
