### ISSUE TITLE
Feature request: Forced stop if this test fails

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#130]
I am running +500 tests on my image.
I do not stop at every  error, rather I run the whole test suite and look at what passed or failed.

Now, there are test whose results are function of others.
(For example, if the apache daemon is not running, I won't be able to see the socket)
How can FORCE my testinfra run to stop on a particular test (because it is really the main issue and it needs to be FIXED first, i.e the other failure are only symptoms of the first problem.)

**Comment by emayssat-ms** [comment]
Note that I am running testinfra with --maxfail 1000 ;-)

**Comment by philpep** [comment]
Not in testinfra scope. See pytest.
