### ISSUE TITLE
File('longfile.log').content_string see to be hanging

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#141]
I am looking at log files (~23K lines at ~80 char each). I am trying to parse the content using content_string and regex. It turns out the content_string is choking , i.e. takes an +oo amount of time. Well, at least, I didn't wait that long.

A work around is to truncate the file prior to reading its content.

**Comment by philpep** [comment]
Yes, transferring the whole file across the network is not a good idea, you should use remote operations instead like "contains()"
