### ISSUE TITLE
Tests within a class raise instance has no __call__ method error

### ISSUE THREAD

**Issue by georgealton** [philpep/testinfra#150]
I'd like to be able to group my tests under classes, However test cases fail due to __call__ error is raised

This code shows the issue
```python

class TestClass:
    def testInClass1(File):
        assert 1

    def testInClass2(File):
        assert File("/").exists
```

**Comment by philpep** [comment]
In a class method, first parameter should be `self`

```
class TestClass:
    def test_method(self, File):
        assert File("/").exists
```

**Comment by georgealton** [comment]
I'm happy to update some of the docs for this - I'll try and raise a PR soon
