### ISSUE TITLE
Please add tags to releases in debian/unstable

### ISSUE THREAD

**Issue by amarao** [philpep/testinfra#153]
Right now there is no way to build debian package from git in CI, expect the head or specific commit.

Normally it is done by adding tag 'debian/1.2.3' to specific commit in debian/unstable branch.

Thanks.

**Comment by philpep** [comment]
Hi, you can build the package using ``git-buildpackage``, here how I do it:

```
git-buildpackage --git-ignore-new --git-pbuilder --git-dist=jessie
```

NB: My packages for testinfra are availables in https://apt.philpep.org

**Comment by amarao** [comment]
But how can I build older version? F.e. I want to build 1.4.0. To be precise, how can I find proper commit in the debian/unstable for it?

**Comment by philpep** [comment]
Its the child commit of 'Merge tag X.Y.Z into debian/unstable', eg for 1.4.0 it's https://github.com/philpep/testinfra/commit/f91d933d5518dea83c82904634b568fa7a538b85

**Comment by amarao** [comment]
But it is very hard to automate. Tags on debian releases allow fixes (f.e. typo in control or changelog, or fix in debian/rules).
