### ISSUE TITLE
Sudo module does not work

### ISSUE THREAD

**Issue by ducva** [philpep/testinfra#179]
I try Sudo module with very simple task

def test_web_private_key(Sudo, File, Command, file):
    with Sudo():
        Command.check_output("whoami")

The command I used to run:

testinfra -vvvsx test_web.py --ssh-config=ssh-config.conf

the result is:

![image](https://cloud.githubusercontent.com/assets/315115/22189352/a2800dda-e14e-11e6-999e-c66a6049742d.png)

**Comment by philpep** [comment]
This is because sudo ask a password. For now there is no way to supply password automatically so your user needs to be allowed to run sudo without password.
