### ISSUE TITLE
I am missing some docs

### ISSUE THREAD

**Issue by guettli** [philpep/testinfra#188]
Thank you for the docs here:

  https://testinfra.readthedocs.io/en/latest/index.html

I am new to testinfra, and maybe you are interested what a new comer is missing on the first page of the docs.

I want to do this:

 1. take vanilla linux operating system
 2. run salt
 3. Do black-box testing: Service should be alive and working.

The examples in the docs show white-box tests. 

... or am I on the wrong track here?

Next: How do you do virtualization? I have seen "vagrant" in the docs. Are other ways of virtualization supported, too?

**Comment by philpep** [comment]
Hi, indeed provisioning and running virtual machines if out of the scope of testinfra.

Usually people use, docker (with custom scripts), vagrant, [molecule](https://github.com/metacloud/molecule) (for ansible), [test-kitchen](http://kitchen.ci/) and probably others.
All these tool are (or can be) integrated with testinfra.

For salt you can find some documentation / code examples here:

https://www.logilab.org/blogentry/7159938 (docker + testinfra)
https://github.com/saltstack-formulas/elasticsearch-formula/ (test-kitchen multi scenarios + testinfra)

**Comment by guettli** [comment]
thank you for your fast reply.

To avoid confusion and wasting time for new comers, I think it would be good to state above on the top of the docs.

**Comment by philpep** [comment]
Testinfra is an equivalent of serverspec, goss or bats but in python. So the main reason you would use testinfra is writing tests in python.

**Comment by guettli** [comment]
I am still learning. What does Testinfra provide, which is not provided by test-kitchen?

**Comment by philpep** [comment]
test-kitchen doesn't do black-box testing by itself, it rely on external tools to do so (testinfra, serverspec, goss or bats).

**Comment by guettli** [comment]
Thank you for your support. My personal issue was solved.

Should I leave this ticket open?
