### ISSUE TITLE
Getting content of the file with 0640 permissions leads to Permission denied

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [philpep/testinfra#191]
Hi,

when trying to do test with filebeat, which obtains the content_str of the file with permission 0o640, I obtain the following exception:

self = <file /etc/filebeat/filebeat.yml>, decode = True

    def _get_content(self, decode):
        out = self.run_test("cat -- %s", self.path)
        if out.rc != 0:
>           raise RuntimeError("Unexpected output %s" % (out,))
E           RuntimeError: Unexpected output CommandResult(command='cat -- /etc/filebeat/filebeat.yml', exit_status=1, stdout=None, stderr='cat: /etc/filebeat/filebeat.yml: Permission denied\n')

Similar test passes without problems, when using serverspec

**Comment by serhiy-yevtushenko** [comment]
One should use --sudo argument, then it works

**Comment by philpep** [comment]
Note that you can activate sudo locally with [the sudo fixture](https://testinfra.readthedocs.io/en/latest/modules.html#sudo)
