### ISSUE TITLE
testinfra is in an unsupported or invalid wheel

### ISSUE THREAD

**Issue by andrewschoen** [philpep/testinfra#201]
When trying to install testinfra==1.6.1 I get the following error:

``testinfra is in an unsupported or invalid wheel``

**Comment by eandersson** [comment]
I am seeing the same issue.

**Comment by andrewschoen** [comment]
However, reverting to 1.6.0 does still work.

**Comment by philpep** [comment]
Just released a new version 1.6.2 with fixed wheel, not sure what happen, but I've done a `git clean -fxd` prior to `python setup.py bdist_wheel` and I tested the new wheel and it worked.

Thanks for reporting !
