### ISSUE TITLE
Socket: Expect Response

### ISSUE THREAD

**Issue by Poogles** [philpep/testinfra#207]
AFAIK this isn't possible, but I'd like to be able to expect a response from a socket when querying, be it the response contains or excludes a value.

The use case for this in my case is the zookeeper 4 letter commands [here](https://zookeeper.apache.org/doc/trunk/zookeeperAdmin.html#sc_zkCommands) where you can check to see the hosts configuration.

The example would be similar to `echo stat | nc localhost 2185 | grep $match` and either passing or failing dependent upon the output.

I'll give something a shot wrapping nc as that seems the easiest if you'd take the PR?

**Comment by philpep** [comment]
You can do it with:

```python
def test_zk4(host):
    output = host.check_output('echo stat | nc localhost 2185')
    # make assertions on output content
    assert 'XXX' in output
```

**Comment by Poogles** [comment]
@philpep Amazing thanks.
