### ISSUE TITLE
Mount options returns list of unicode strings

### ISSUE THREAD

**Issue by rwaweber** [philpep/testinfra#221]
It's possible I'm being thick here(I'm probably missing a python 3 compatibility thing), but when using the options attribute of the mount_point module, it seems to return unicode strings, which doesn't seem to fit the documentation below:

https://github.com/philpep/testinfra/blob/master/testinfrbya/modules/mountpoint.py#L75-#L83

EDIT:
The same also seems to be occurring with the User module, for the groups attribute.

#### Reproduction ####
Been working on vagrant bento/debian-8.8, using python 2.7.9, and testinfra 1.6.4
```python

import testinfra
conn = testinfra.get_host('local://')
print(conn.mount_point('/').options)
print(conn.user('root').groups)

```

**Comment by philpep** [comment]
Not sure to understand your issue. Yes it should return a list of unicode string (unicode type in py2 and str type in py3), what's the issue then ?

**Comment by rwaweber** [comment]
Ahh okay, so this was me being thick!

I didn't know that it was a python2/python3 compatibility measure to return unicode strings in python2. I also didn't realize that that all strings are actually Unicode strings in Python 3. Sorry about that!

Closing!
