### ISSUE TITLE
Remote TCP check

### ISSUE THREAD

**Issue by giovtorres** [philpep/testinfra#224]
Is there a way to do a remote TCP check?  The Socket module runs on the system-under-test and checks local sockets.  It would be helpful to have the ability to remotely check if a host is listening and reachable on ports 80/443, for example.

Thanks.

**Comment by philpep** [comment]
You can use python standard library or third party module to do that, for instance using [socket](https://docs.python.org/3/library/socket.html) module or [requests](http://docs.python-requests.org/en/master/) for http.

**Comment by giovtorres** [comment]
Sure.  That's fine.  I thought it might be helpful to have this type of check incorporated into testinfra's modules.  I was envisioning a 'monitoring-as-code' paradigm that would use Testinfra to replace something like Nagios for doing infrastructure monitoring/testing.
