### ISSUE TITLE
Support alpine docker images

### ISSUE THREAD

**Issue by bbaassssiiee** [philpep/testinfra#228]
My Dockerfile starts with:

`FROM nginx:1.12-alpine`

In my Dockerfile I want to pull images based on Alpine because these are way smaller than Ubuntu, Centos, and the like. Alpine uses BusyBox so command options are limited. 

[BusyBox Commands]https://busybox.net/downloads/BusyBox.html#commands )

**Comment by philpep** [comment]
I'll accept PR for this, there is probably just enhancement in ``SystemInfo`` and ``Package`` and maybe ``Service`` module to get it working with Alpine.
