### ISSUE TITLE
xpost from saltstack issue backlog

### ISSUE THREAD

**Issue by adeck** [philpep/testinfra#229]
Looks like no one is working on:
https://github.com/saltstack/salt/issues/40916

It's still an issue in the current version of salt. Since it's the salt testinfra integration, I though it might be useful to widen the visibility to both teams.

**Comment by philpep** [comment]
This third party module for salt was using a (kind of) private API that has been broken since. This has been fixed now. I'll consider the existence of this usage now. Thanks for reporting.
