### ISSUE TITLE
The Examples documentation for Test Docker Images has flaws

### ISSUE THREAD

**Issue by codylane** [philpep/testinfra#242]
Hello,

I was playing with the 'Test docker Images' here: https://testinfra.readthedocs.io/en/latest/examples.html#test-docker-images

I had implemented a single parameterized test using the `docker_images` decorator as suggested and noticed that the behavior was unexpected and caused me to troubleshoot why my tests where using the wrong OS for more than a few hours.  

Here's an example that will reproduce this.

VERSION INFO
===========
- testinfra version: 1.6.5
- docker version: 17.04
- python version: 2.7.13
- pytest version: 3.2.1

# Step 1
- Configure your `tests/conftest.py` as recommended in the link above.

# Step 2
- Implement some test
```
# tests/test_flaw.py

@pytest.mark.docker_images('centos:6')
def test_user_exists_on_centos6(host):
    root_user = host.user('root')

    assert root_user.exists
    assert root_user.shell == '/bin/base'
    assert root_user.gecos == 'root'
    assert root_user.home == '/root'
    assert root_user.group == 'root'

@pytest.mark.docker_images('centos:7')
def test_user_exists_on_centos7(host):

    # This will catch the flawed behavior.  On my system the system under test was CentOS 6.x!
    assert host.system_info.release == '7'

    root_user = host.user('root')

    assert root_user.exists
    assert root_user.shell == '/bin/base'
    assert root_user.gecos == 'root'
    assert root_user.home == '/root'
    assert root_user.group == 'root'
```
- Behavior of the above is not what you expect.  Yes, I can combine the test into a single test and just use the decorator `@pytest.mark.docker_images('centos:6', 'centos:7')` but the flawed behavior is the same. 

- We expect the two tests to run under two different docker containers one for `centos:6` and one for `centos:7`.  However, what I noticed was that I was executing two tests under `centos:6` even when the second test should have only executed on `centos:7`.  The assertion in the second test should expose the unexpected behavior that I'm noticing.  

I'll provide the example failure later.

**Comment by philpep** [comment]
Yes, I think it's a pytest bug. testinfra has several hacks in it's own test suite to "fix" this: https://github.com/philpep/testinfra/blob/master/test/conftest.py#L105

I simplified the docker example so it's simplier to understand (and is working): https://testinfra.readthedocs.io/en/latest/examples.html#test-docker-images
