### ISSUE TITLE
Testing testinfra

### ISSUE THREAD

**Issue by amitsaha** [philpep/testinfra#25]
Hi, how do we run the tests in ``test``? When i tried to run them using ``py.test``, I got errors such as:

```
 fixture 'Command' not found
```

I understand the issue. Shouldn't we be importing these classes?

**Comment by philpep** [comment]
Hi, testinfra use testinfra for testing :)

We have two classes of tests: Normal tests can be run with the command `testinfra testinfra` and integration tests that use vagrant and docker images in `./images`.

See https://github.com/philpep/testinfra/blob/master/CONTRIBUTING.rst for running the complete test suite.
