### ISSUE TITLE
target a specific inventory host during a test

### ISSUE THREAD

**Issue by leseb** [philpep/testinfra#254]
Hey,

Thanks for this project! It's working great.

I have one question, we use the Ansible connection for our tests and I'd like to know if it's possible to call a particular host variable from the host the test is running on.

I'd like to use something like this: `{{ hostvars[groups[mon_group_name][0]]['ansible_hostname'] }}`

Thanks in advance!

**Comment by madrover** [comment]
Have you tried [get_variables()](http://testinfra.readthedocs.io/en/latest/modules.html#testinfra.modules.ansible.Ansible.get_variables), @leseb?

**Comment by leseb** [comment]
I think I solved that, I just don't remember how. Although I think your answer is what I was looking for. Closing this, thanks @madrover.
