### ISSUE TITLE
Documentation: SystemInfo has method hostname, but nothing in docs

### ISSUE THREAD

**Issue by amarao** [philpep/testinfra#260]
Introspection shows that SystemInfo has mehtod `hostname`:

```
dir(testinfra.modules.SystemInfo)
...
... 'group', 'hostname', 'release'...
```
and it works: `assert ssh_backend.SystemInfo.hostname == 'myhostname'`

But documentation http://testinfra.readthedocs.io/en/latest/modules.html#testinfra.modules.systeminfo.SystemInfo has nothing about it.

**Comment by philpep** [comment]
Hi, this method (and user, uid, group, gid) where added by mistake and are not part of the public api. I dropped them.

FYI, hostname is (was) equivalent to

```
>>> host.check_output('hostname -s')
```

Thanks for reporting and pointing me on this!
