### ISSUE TITLE
Feature Request: Docker module

### ISSUE THREAD

**Issue by blackillzone** [philpep/testinfra#264]
Is this possible to add a module, to check if a docker service is up (like the service module would currently do) ?

I would see something like this (with more or less functionalities):

```
class Docker(name)
     is_running
Test if container is running

     is_listening
Test if container is listening to ports

     version
Return version of the image that the container is running
```

What do you think about this ? Could it be relevant to add it ?

**Comment by sashgorokhov** [comment]
Sounds interesting, I could submit a PR for that, though I am not currently familiar with testinfra, so it could take some time. @philpep, what do you think?

**Comment by philpep** [comment]
I think this could be useful to have a docker module. Probably ansible or salt source code could be an inspiration.

**Comment by mludy** [comment]
Hi Guys, what is the status of it ? Having docker module would be very useful with dockerized environments test

**Comment by ecks** [comment]
please take a look at pull request #300

**Comment by Kilo59** [comment]
@blackillzone I think this issue can be closed. The PR mentioned above has been already been accepted and merged.
