### ISSUE TITLE
pip 10.x incompatibility

### ISSUE THREAD

**Issue by acrewdson** [philpep/testinfra#299]
Hello,

`pip` 10 was pushed to pypi for the first time a few days ago. It looks like they changed the `pip list` output, and so this regex no longer works as expected https://github.com/philpep/testinfra/blob/e91b0c730dd8425fb608606132a21092c5003d08/testinfra/modules/pip.py#L32

Would you be interested in a PR?

Thanks!

**Comment by philpep** [comment]
Yes, I noticed that but didn't have time to fix this yet. PR would be greatly appreciated :)

**Comment by acrewdson** [comment]
@philpep 👍 will do, thanks

**Comment by acrewdson** [comment]
closing, see https://github.com/philpep/testinfra/pull/301
