### ISSUE TITLE
SysvService has a subtle flaw if rc?.d directories are symlinks

### ISSUE THREAD

**Issue by codylane** [philpep/testinfra#327]
While testing this afternoon, I noticed another small issue if a system under test uses the `SysvService` to check for service state.  This one is very subtle and didn't catch my eye right away.

https://github.com/philpep/testinfra/blob/master/testinfra/modules/service.py#L93-L98

could be changed to this which follows symlinks incase the `rc?.d` are symlinks because on some Linux machines they are indeed symlinks.  

```
diff --git a/testinfra/modules/service.py b/testinfra/modules/service.py
index 7b3b197..ad1b7e0 100644
--- a/testinfra/modules/service.py
+++ b/testinfra/modules/service.py
@@ -133,7 +133,7 @@ class SysvService(Service):
     @property
     def is_enabled(self):
         return bool(self.check_output(
-            "find /etc/rc?.d/ -name %s",
+            "find -L /etc/rc?.d/ -name %s",
             "S??" + self.name,
         ))

```

Here is an example of a Linux box with `rc?.d` symlinks.  The change above should behave the same with or without symlinks.  Without the patch, `is_enabled` would always return `False`.

`cat /etc/redhat-release`
```
CentOS release 6.9 (Final)
```

` ls -ld /etc/rc?.d`
```
lrwxrwxrwx 1 root root 10 Apr  2 18:48 /etc/rc0.d -> rc.d/rc0.d
lrwxrwxrwx 1 root root 10 Apr  2 18:48 /etc/rc1.d -> rc.d/rc1.d
lrwxrwxrwx 1 root root 10 Apr  2 18:48 /etc/rc2.d -> rc.d/rc2.d
lrwxrwxrwx 1 root root 10 Apr  2 18:48 /etc/rc3.d -> rc.d/rc3.d
lrwxrwxrwx 1 root root 10 Apr  2 18:48 /etc/rc4.d -> rc.d/rc4.d
lrwxrwxrwx 1 root root 10 Apr  2 18:48 /etc/rc5.d -> rc.d/rc5.d
lrwxrwxrwx 1 root root 10 Apr  2 18:48 /etc/rc6.d -> rc.d/rc6.d
```

`ls -ld /etc/rc.d`
```
drwxr-xr-x 10 root root 4096 Apr  2 18:49 /etc/rc.d
```

`ls -l /etc/rc.d`
```
drwxr-xr-x 2 root root 4096 Apr  2 18:49 init.d
drwxr-xr-x 2 root root 4096 Apr  2 18:49 rc0.d
drwxr-xr-x 2 root root 4096 Apr  2 18:49 rc1.d
drwxr-xr-x 2 root root 4096 Apr  2 18:49 rc2.d
drwxr-xr-x 2 root root 4096 Apr  2 18:49 rc3.d
drwxr-xr-x 2 root root 4096 Apr  2 18:49 rc4.d
drwxr-xr-x 2 root root 4096 Apr  2 18:49 rc5.d
drwxr-xr-x 2 root root 4096 Apr  2 18:49 rc6.d
```

**Comment by philpep** [comment]
Good catch! This might explain several bugs around centos 6 & services. Your patch looks good to me, you can submit it as it in a PR ? Thanks!

**Comment by codylane** [comment]
Cool, i'll take a stab at it.  Would you be ok if I add a `centos_6` container to the [images](https://github.com/philpep/testinfra/tree/master/images)?  I feel like it might be a good idea since CentOS is still under support and will not be EOL until [2020](https://wiki.centos.org/About/Product).

If you don't like the idea of me adding a `centos_6` container, then I can totally accomplish this with unit tests.  

In either case, I'm hoping to have this in to you either tonight or tomorrow.  I have to work today and cannot spend time on this until after work.

**Comment by codylane** [comment]
PR #329 request submitted.  Tested this on multiple systems, let's hope Travis works today. ;)
