### ISSUE TITLE
Access to playbook vars in testinfra

### ISSUE THREAD

**Issue by dangoncalves** [philpep/testinfra#351]
Description
--------------
When setting some variables in default/main.yml or in vars/main.yml, these variables are accessible during the playbook execution. But we cannot access to them during the verify sequence with testinfra as a verifier.

This is probably due to the fact that testinfra doesn't run within the playbook (see https://github.com/philpep/testinfra/issues/266#issuecomment-346470406). It could be interesting if we had a method that permit to access to the playbook variables during the tests.book execution. But we cannot access to them during the verify sequence with testinfra as a verifier.

How to reproduce
----------------------
`git clone https://github.com/dangoncalves/testinfra_bug_variables.git`
`cd testinfra_bug_variables`
`molecule test`

Versions
-----------
Ansible: 2.6.1

Molecule: 2.16.0

Testinfra: 1.14.0

**Comment by lwm** [comment]
Related ticket: https://github.com/philpep/testinfra/issues/345.

**Comment by dangoncalves** [comment]
#345 seems to be the good place to discuss. Closing this ticket
