### ISSUE TITLE
Add a Network / Host / Dns module

### ISSUE THREAD

**Issue by philpep** [philpep/testinfra#358]
This module could provide network tests like ping / open tcp udp connections / dns resolution.

Example:

```
assert host.network.resolve('google.com', type='NS', server='8.8.8.8') == set(['ns{}.google.com'.format(i) for i in range(1, 5)])
assert host.network.resolve('example.com', type='A').ttl = 1982
# ---> this could be implemented by using a smart object that resolve to a host set with additional attributes
assert host.network.reachable('tcp://google.com:443')
assert host.network.reachable('icmp://google.com')
assert host.network.not_reachable('tcp://google.com:22', timeout=3)
```

I think the implementation could be a mix of `dig`, `nc`, `ping`.

Please feel free to explain what you want to do with such module.

**Comment by philpep** [comment]
Also we should see what feature has goss, inspec and serverspec, there might be good idea to reuse.

**Comment by ruimoreira** [comment]
Thank you for your input, I will look into this.

**Comment by ruimoreira** [comment]
Looking at goss, it seems that they do what i was proposing to do, 1 module for dns tests and another for interface related tests. For now they have one assertion afaik, and that's to test if the record is resolvable, which is more or less what I had implemented. I understand that it was not enough but my hope at the time was that it would gain momentum and lead to more assertions being required and implemented at a later time.  
As far as inspec goes I cannot see a dns or even much of network tests apart from what appears to be interface settings, that does seem to be quite elaborate. In both cases they seem to test for things like , speed, state of interface (up or down),  goss is quite simple but inspec seems to implement a few interesting bits. 

As far as network goes I think the following assertions should be implemented

 - ip of interface
 - Speed 
 - MTU 
 - state (up or down) 
 
In terms of DNS 

 - Assert record is resolvable
 - Assert record is of expected type 
 - Assert ttl is as expected

In terms of network related assertions 

 - Assert host is pingable 
 - Assert host is recheable on a specific socket (ip address and protocol) 

Please share any more ideas you might have .

**Comment by skhoroshavin** [comment]
Speaking of inspec/serverspec: you can take a look at their implementation of similar feature here:
https://github.com/mizzy/specinfra/blob/master/lib/specinfra/command/base/host.rb
https://github.com/inspec/inspec/blob/master/lib/resources/host.rb

Also please note that some systems don't have netcat installed by default, furthermore some consider having netcat installed on server as a potential security breach (mainly due to it's ability to listen on some port and execute arbitrary stuff), it seems it's the reason why Inspec implemented port checks using bash as a fallback:
https://github.com/inspec/inspec/blob/master/lib/resources/host.rb#L155

**Comment by skhoroshavin** [comment]
@philpep 
> Please feel free to explain what you want to do with such module.

My main use case is testing routing and vpn configurations, making sure that everything works as expected.

**Comment by skhoroshavin** [comment]
@ruimoreira 
+1 for adding something like `is_up` to interface. Speaking of additions to existing modules - it would also be useful to improve `Socket` module so it can check that socket is not just listening, but is opened by specific process.

**Comment by ruimoreira** [comment]
@skhoroshavin @philpep  what's your opinion regarding keeping these two features (dns and networking ) separate or should we use the same module for both tasks ?

**Comment by skhoroshavin** [comment]
@ruimoreira I think they should be same module, in my opinion this will lead to more compact and easy to read tests.

**Comment by philpep** [comment]
Thank you @ruimoreira and @skhoroshavin for digging into what other tools are doing !
I also feel that a single module (let's say "network") would be easier to work with, not a strong opinion though.

This new module could also replace the "interface" module (which is quite poor, only 3 functions).

+1 for having an integration between socket and process module, I opened #367 but I feel this new network module might also need such integration.

**Comment by skhoroshavin** [comment]
@philpep I like idea of creating single "network" module (but probably name like "remote" would be better, because it's focused on checking whether some remote host is resolvable or reachable), but I don't think that merging into it functionality of "interface" module is right. Interface module is about querying state of local network interfaces and while it would be fine to extend its functions I think it doesn't overlap at all with "network/remote"

**Comment by ruimoreira** [comment]
I was wondering how we can collaborate, I would like to contribute to this module, and more modules in the future ... any ideas ?

**Comment by philpep** [comment]
@ruimoreira @skhoroshavin feel free to open PRs. Now we have a plan about how the module should be implemented, I'm ok to add features incrementally to it, so a first try implementing "revolve()" or "reachable()" with basic tests is fine to me. For the module name, I still prefer "network" than "remote", but I'm open to other suggestions.
And, sorry, it seems lot of contributors to testinfra feel that submitting PRs and asking questions on issues are like throw a stone in water. But I maintain testinfra on my free time and never get paid for. Actually reviewing a PR takes me a lot of time to me because I'm quite rigorous regarding regressions or broken new features which may generate even more work after being merged. So new features are very "low priority" for me. On another side, I understand contributors expect a fast feedback, I'll try to take at least 5 min per week for that.
But I really appreciate how this new module is designed here, so I'm waiting for a PR :)

**Comment by skhoroshavin** [comment]
@philpep Finally there is a PR #402, hopefully you'll find some time to review

**Comment by skhoroshavin** [comment]
Tests are still failing, however it would be great to have some early feedback if my approach is good enough.

**Comment by skhoroshavin** [comment]
@philpep I've updated PR with documentation and usability improvements
