### ISSUE TITLE
How can I use a wildcard in a content assertion

### ISSUE THREAD

**Issue by cavepopo** [philpep/testinfra#369]
Hi,

I guess this is not directly related to testinfra (more python stuff or pytest stuff), but I did not know how to do this, so : 
I would like to use a wildcard inside a content assertion, something along : 
` assert (host_ip + '\t\t' + fqdn + '*' + hostname) in content`

is it possible at all or is it not in the pytest philosophy and I am handling this the wrong way ?

Thanks

**Comment by philpep** [comment]
Hi, this is indeed a python question.

I think you can write:

```
assert content.startswith(host_ip + '\t\t' + fqdn)
assert content.endswith(hostname)
```

or use the regexp module

```
import re
assert re.match('^{}\t\t{}.*{}'.format(host_ip, fqdn, hostname), content)
```

**Comment by cavepopo** [comment]
Arf the 'endswith', I should have though about this ....

Thanks a lot for the regexp insight, and for answering a question that is not directly related to this product.
