### ISSUE TITLE
fixture 'File' not found

### ISSUE THREAD

**Issue by makarandkm** [philpep/testinfra#37]
I have installed testinfra-1.0.0.0a13 version successfully, but when i run sample test.. it gives me following error....

 fixture 'File' not found
        available fixtures: tmpdir_factory, pytestconfig, cache, recwarn, monkeypatch, record_xml_property, capfd, capsys, tmpdir
        use 'py.test --fixtures [testpath]' for help on them.

platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1 -- /usr/bin/python2.7

Can some one help me...

**Comment by philpep** [comment]
Hi,

It's seems testinfra was not installed correctly. How you have installed it ?

**Comment by philpep** [comment]
Can you run this command succesfully ?

```python -c 'import testinfra; print(testinfra)'```

**Comment by makarandkm** [comment]
[root@localhost ~]# python -c 'import testinfra; print(testinfra)'
<module 'testinfra' from '/opt/python2.7.10/lib/python2.7/site-packages/testinfra/__init__.pyc'>

**Comment by philpep** [comment]
Can you run this ?

```testinfra --version``` and ``py.test --version```

**Comment by makarandkm** [comment]
root@localhost]# testinfra --version
This is pytest version 2.8.2, imported from /opt/python2.7.10/lib/python2.7/site-packages/pytest.pyc

[root@localhost ~]# py.test --version
This is pytest version 2.8.2, imported from /opt/python2.7.10/lib/python2.7/site-packages/pytest.pyc

**Comment by philpep** [comment]
This is weird, ``--version`` should print something like:

```
This is pytest version 2.8.2, imported from /home/phil/venvs/testinfra/local/lib/python2.7/site-packages/pytest.pyc
setuptools registered plugins:
  testinfra-1.0a4.post64 at /home/phil/src/testinfra/testinfra/plugin.pyc
```

I think you have a old or buggy version of setuptools that doesn't handle entry_points correctly.

Can you run ```pip list``` or ``python -c 'import setuptools; print(setuptools.__version__)`` ?

Maybe installing in a virtualenv is a better choice:

```
virtualenv v
source v/bin/activate
pip install testinfra
testinfra --version
```

This will create a virtualenv inside `./v` and install testinfra in it

**Comment by makarandkm** [comment]
Thanks a lot , now its working,  I tried with your virtual environment method and also latest version of setuptools.

**Comment by MhdAli** [comment]
I hit the same issue in here I'm using:

- CentOS 6.6
- Python 2.6.6
- py.test 2.8.7
- testinfra 1.0.1

I fixed it by install it using `easy_install` instead of installing it using `pip`, I don't know why exactly, I don't want to spent time to figure out the root cause :)

I though it worth sharing.

**Comment by promodhyman** [comment]
I also hit this issue with RHEL6.  I think the root cause was a pip installation that came from Pypi, but a setuptools from the RHEL repository,  Upgrading setuptools using pip solved my issue.

**Comment by mlsmaycon** [comment]
I think I have checked what promodhyman wrote by upgrading pip and pytest worked for me:

pip install --upgrade pip
pip install --upgrade pytest
