### ISSUE TITLE
sysctl not in PATH

### ISSUE THREAD

**Issue by camillehuot** [philpep/testinfra#376]
Hi

https://github.com/philpep/testinfra/blob/99b9b6436ededf30496f47de53effda3a96a6cea/testinfra/modules/sysctl.py#L29

What if sysctl is not in the PATH? (typically /sbin/sysctl) 
Would you recommend to depend on another playbook or role to configure the user to change the PATH before being able to run this test?
Or to run this test with root privilege (which should have the correct PATH), while no root privileges are required?

Could I suggest that you try to find sysctl in /sbin if it is not in the PATH? (Actually you would just have to append /sbin at the end of the user's path when executing this command)

Today I'm getting this error:
    =================================== FAILURES ===================================
    _______________________ test_sysctls[ansible://instance] _______________________

    host = <testinfra.host.Host object at 0x7ff31ab701a8>

        def test_sysctls(host):
    >       assert host.sysctl('fs.file-max') == '6815744'

    tests/test_default.py:11:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = <sysctl>, name = 'fs.file-max'

        def __call__(self, name):
    >       value = self.check_output("sysctl -n %s", name)
    E       AssertionError: Unexpected exit code 127 for CommandResult(command='sysctl -n fs.file-max', exit_status=127, stdout='', stderr='/bin/sh: sysctl: command not found')
    E       assert 127 == 0
    E        +  where 127 = CommandResult(command='sysctl -n fs.file-max', exit_status=127, stdout='', stderr='/bin/sh: sysctl: command not found').rc

    ../../../../ansible-virtualenv/lib/python3.6/site-packages/testinfra/modules/sysctl.py:29: AssertionError
    =========================== 1 failed in 2.39 seconds ===========================

**Comment by philpep** [comment]
Hi, yes it's a bug. We already have such troubles with other commands and we have code to handle this. Should be fixed quickly, thanks for reporting.

**Comment by camillehuot** [comment]
Fixed and delivered, awesome, you saved my day! Thanks
