### ISSUE TITLE
mutiple hosts with different username and passwords

### ISSUE THREAD

**Issue by makarandkm** [philpep/testinfra#38]
I have use case where i will be creating new machines and setting up different users for access. So is there any way i can provide different username and passwords using testinfra.

**Comment by philpep** [comment]
Testinfra cannot handle password yet #34 , so you must setup a password less key or use ssh-agent.

But you can connect with different users:

```testinfra --hosts=user1@host1,user2@host2```

You can also provide a ssh-config with ``--ssh-config``

See also the documentation for connection backends: https://testinfra.readthedocs.org/en/latest/backends.html
