### ISSUE TITLE
testinfra 1.17.0 wheel installation does not work under python3

### ISSUE THREAD

**Issue by cboylan** [philpep/testinfra#380]
The wheel on pypi for testinfra 1.17.0 declares an unconditional dependency on importlib which should be for python 2.6 only. Unfortunately this causes testinfra installations under python3 (and probably python2.7?) to fail:

```
Collecting importlib (from testinfra)
  Using cached https://files.pythonhosted.org/packages/31/77/3781f65cafe55480b56914def99022a5d2965a4bb269655c89ef2f1de3cd/importlib-1.0.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/clark/tmp/git/testinfra/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/home/clark/tmp/git/testinfra/venv/lib64/python3.6/distutils/__init__.py", line 4, in <module>
        import imp
      File "/home/clark/tmp/git/testinfra/venv/lib64/python3.6/imp.py", line 19, in <module>
        from importlib._bootstrap import _ERR_MSG, _exec, _load, _builtin_from_name
    ModuleNotFoundError: No module named 'importlib._bootstrap'
```

Note installing via `pip install /some/path/to/testinfra/git/repo` works as does `pip install --no-binary :all: testinfra`.

I think this issue is purely with the generated wheel. Possibly because python2.6 is being used to generate the wheel which results in a not actually universal wheel.

The easiest workaround is likely to stop publishing wheels until python2.6 doesn't need to be supported. Or to use an extras_require in the setup() method for python2.6 to install importlib.

**Comment by ryan-rs** [comment]
Reproduced this issue under Python 3.5 and 3.6.

**Comment by heterodyned** [comment]
Glad to see this! here, I was going to create an issue for this.

**Comment by philpep** [comment]
Woops, thanks for reporting this. I dropped the broken wheel from pypi.org
