### ISSUE TITLE
Logo license (usage guidelines)

### ISSUE THREAD

**Issue by yasny** [philpep/testinfra#383]
Would it be possible to add some information regarding the license for the [Testinfra logo](https://github.com/philpep/testinfra/blob/master/doc/source/_static/logo.svg) like [Molecule has for their logo](https://molecule.readthedocs.io/en/latest/#license)? Or is everything being released under the [Apache License 2.0](https://github.com/philpep/testinfra/blob/master/LICENSE)?

The reason I'm asking is because I'm going to be giving a presentation at a large IT conference and I would like to use the Testinfra logo on my slides when I talk about how our company is testing Ansible roles with [Molecule](https://molecule.readthedocs.io/). I'm pretty sure this usage is OK, but my company is giving me a hard time with regards to copyrights/trademarks.

**Comment by philpep** [comment]
Hi, thanks for asking, I don't known about what is the more suitable license for the logo, I think I can use "Creative Commons NoDerivatives 4.0 License" just like molecule logo.
Any advice @douardda ?
