### ISSUE TITLE
Correctly parsing passwords containing `@` and `?`

### ISSUE THREAD

**Issue by jmillxyz** [philpep/testinfra#387]
We're using testinfra to verify that automated software installs occur as planned. It's great so far, thank you!

However, AWS will often generate windows passwords that contain `@` and `?`, which confuses testinfra's argument parsing.

For reference, our current host string looks like this:
```
winrm://username:password@ip_address:port?no_verify_ssl=true
```

We'd like to help -- is there a suggested way to approach this?

The parsing algorithm we had in mind would be: `.split("?")` on the last occurrence of a `?` in the string in order to identify arguments like `no_verify_ssl`.

We'd use the same approach for `@` -- splitting the string only on the last occurrence of that character to correctly identify passwords vs ip_address.

**Comment by philpep** [comment]
I think the right way to handle this is to urlencode your password. `p@assword?` -> `p%40ssword%3F`.

But I'm pretty sure testinfra will not decode it back, this is a bug, thanks for reporting it!
