### ISSUE TITLE
Backend setup and teardown process.

### ISSUE THREAD

**Issue by dmajere** [philpep/testinfra#4]
For some backends (eg docker backend) it would be nice to have setup and teardown phases. For now container creation and removal processes are held in run method, which is not optimal.
It would be preferable to have setup process during which docker container could be created and tear down process during which its removal could be executed. It would really quicken testing.

**Comment by philpep** [comment]
Hi,

We must think if the setup/teardown must occur at function or session level. Maybe both are needed.

The session level can be implemented easily by adding a `request.addfinalizer()` to `testinfra_backend` (the root fixture of testinfra).

**Comment by philpep** [comment]
For docker, I think a teardown at function level will be a better behavior than at session level.
