### ISSUE TITLE
Problem with tests over ssh backend

### ISSUE THREAD

**Issue by mchugh19** [philpep/testinfra#41]
Howdy, 

I just created a simple test to check for a few services running:
```
def test_passwd_file(File):
  passwd = File("/etc/passwd")
  assert passwd.contains("root")
  assert passwd.user == "root"

def test_nimsoft(Service):
  nimsoft = Service("nimbus")
  assert nimsoft.is_running

def test_uxauthd(Service):
  uxauthd = Service("uxauthd")
  assert uxauthd.is_running

def test_sshd(Service):
  sshd = Service("sshd")
  assert sshd.is_running
```

If I attempt to check a host via ssh, I'm told the services are failed. But if I copy the file to the remote host, install testinfra, and run it locally, everything passes:

```
$ testinfra --connection=ssh --hosts=hcladmin@evprappbpwl01.domain.name --sudo test_integrations.py 
======================= test session starts =
platform linux -- Python 3.5.0+, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
rootdir: /home/xian/work/validater, inifile: 
plugins: testinfra-1.0.0.0a16
collected 4 items 

test_integrations.py .FFF

================== FAILURES =======
_____________________________ test_nimsoft[ssh://evprappbpwl01.domain.name] ____

Service = <service None>

    def test_nimsoft(Service):
      nimsoft = Service("nimbus")
>     assert nimsoft.is_running
E     assert <service nimbus>.is_running

test_integrations.py:8: AssertionError
____________________ test_uxauthd[ssh://evprappbpwl01.domain.name] 

Service = <service None>

    def test_uxauthd(Service):
      uxauthd = Service("uxauthd")
>     assert uxauthd.is_running
E     assert <service uxauthd>.is_running

test_integrations.py:12: AssertionError
_______________________ test_sshd[ssh://evprappbpwl01.domain.name] 

Service = <service None>

    def test_sshd(Service):
      sshd = Service("sshd")
>     assert sshd.is_running
E     assert <service ssh>.is_running

test_integrations.py:16: AssertionError
========================= 3 failed, 1 passed in 2.51 seconds 
```

Versus running it on the host
```
[hcladmin@evprappbpwl01 ~]$ testinfra --sudo test_integrations.py
=========== test session starts =============================
platform linux2 -- Python 2.6.6, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
rootdir: /home/hcladmin, inifile:
plugins: testinfra-1.0.0.0a16
collected 4 items

test_integrations.py ....

======================= 4 passed in 0.78 seconds ===========
```

Thanks!

**Comment by philpep** [comment]
Hi, can you test with `-vvvsx` options ?

Maybe there is an hidden error related to ssh or sudo.

**Comment by philpep** [comment]
Have you the same error with `--connection=paramiko` ?

**Comment by mchugh19** [comment]
Here you are...

```
xian@xian-work:~/work/validater$ testinfra --connection=ssh --hosts=hcladmin@evprappbpwl01.domain.name --sudo -vvvsx test_integrations.py 
============================= test session starts =======
platform linux -- Python 3.5.0+, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python3.5
cachedir: .cache
rootdir: /home/xian/work/validater, inifile: 
plugins: testinfra-1.0.0.0a16
collecting 0 itemsIgnored argument: connection = ssh
Ignored argument: ansible_inventory = None
collected 4 items 

test_integrations.py::test_passwd_file[ssh://evprappbpwl01.domain.name] PASSED
test_integrations.py::test_nimsoft[ssh://evprappbpwl01.domain.name] FAILED

========================================= FAILURES ======
_______ test_nimsoft[ssh://evprappbpwl01.domain.name] ___

Service = <service None>

    def test_nimsoft(Service):
      nimsoft = Service("nimbus")
>     assert nimsoft.is_running
E     assert <service nimbus>.is_running

test_integrations.py:8: AssertionError
!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================= 1 failed, 1 passed in 2.15 seconds ===========
```


and it appears to be the same with paramiko

```
xian@xian-work:~/work/validater$ testinfra --connection=paramiko --hosts=hcladmin@evprappbpwl01.domain.name --sudo -vvvsx test_integrations.py 
============ test session starts =====================
platform linux -- Python 3.5.0+, pytest-2.8.3, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python3.5
cachedir: .cache
rootdir: /home/xian/work/validater, inifile: 
plugins: testinfra-1.0.0.0a16
collecting 0 itemsIgnored argument: ansible_inventory = None
Ignored argument: connection = paramiko
collected 4 items 

test_integrations.py::test_passwd_file[paramiko://evprappbpwl01.domain.name] /usr/local/lib/python3.5/dist-packages/paramiko/client.py:645: UserWarning: Unknown ssh-rsa host key for evprappbpwl01.domain.name: b'f9397b36b08b54ac90631bb5319a0ce5'
  (key.get_name(), hostname, hexlify(key.get_fingerprint())))
PASSED
test_integrations.py::test_nimsoft[paramiko://evprappbpwl01.domain.name] FAILED

================= FAILURES ==================
_______________ test_nimsoft[paramiko://evprappbpwl01.domain.name]_______________________

Service = <service None>

    def test_nimsoft(Service):
      nimsoft = Service("nimbus")
>     assert nimsoft.is_running
E     assert <service nimbus>.is_running

test_integrations.py:8: AssertionError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================= 1 failed, 1 passed in 1.03 seconds =====
```


I've got the passwd file tests in there, and they always pass. So it seems to be related to the service check.

**Comment by philpep** [comment]
Yep. This can be related to python 3.5 too.

What is your target distribution ? And do you use systemd, sysv or upstart ?

**Comment by philpep** [comment]
Can you paste the output of:

`service nimbus status; echo $?` and `systemctl is-active nimbus; echo $?`

**Comment by philpep** [comment]
It can also be an issue with `$PATH`, ssh and sudo. I see that sudo exit with a status code 1 when the command cannot be found in `$PATH`.

**Comment by mchugh19** [comment]
I'm attempting to run the tests on a RHEL 6.5 machine from my desktop (which is current kubuntu)

I'm pretty sure all the services that I'm attempting to monitor are launched from the sysv compatibility layer of upstart.


```
$ sudo service nimbus status; echo $?
NIMBUS_USER: root
NIMBUS_ROBOT_ROOT: /opt
nimbus (pid 2122) is running...
0
```

Since this is rhel 6, there is no systemd, so I don't have systemctl.

As far at PATH goes, I'd think having testinfra ssh to run sudo would be the same as my doing it manually. Also, when I ran the tests locally, they succeeded.

In case the python stack trace might help narrow down any issues, I've pasted it here: http://pastebin.com/dS6YEAvy

**Comment by philpep** [comment]
Ok, so the command that testinfra try to run is:

`ssh hcladmin@evprappbpwl01.domain.name sudo service nimbus status; echo $?`

Is this command running successfully from your desktop ?

**Comment by mchugh19** [comment]
Ah ah! Interestingly enough, it fails:
```
$ ssh hcladmin@evprappbpwl01.domain.name sudo service nimbus status; echo $?
      --------------------------------------------------------------------------
     BANNER
      --------------------------------------------------------------------------
sudo: service: command not found
1
```

While fully ssh'ing to the machine, then running the commands work

```
$ ssh hcladmin@evprappbpwl01.domain.name
      --------------------------------------------------------------------------
    BANNER
      --------------------------------------------------------------------------
Last login: Tue Dec  1 19:08:57 2015 from xian-work.domain.name
[hcladmin@evprappbpwl01 ~]$ sudo service nimbus; echo $?
NIMBUS_USER: root
NIMBUS_ROBOT_ROOT: /opt
Starting NimBUS:

0
```

I just edited service.py to hardcode service as /sbin/service, and now the tests pass. So it now works for me. 


Thanks!

**Comment by philpep** [comment]
Yeah it's an issue with `$PATH` and ssh.

Is this command running successfully ?

`ssh hcladmin@evprappbpwl01.domain.name sudo /bin/sh -c 'service nimbus status'; echo $?`

**Comment by muffl0n** [comment]
I had some similar problems while developing ansible playbooks under Ubuntu 14. I solved this with using "sudo -E":
```
-E, --preserve-env
                 Indicates to the security policy that the user wishes to preserve their existing environment variables.  The security policy may return an error if the user does not have per‐
                 mission to preserve the environment.
```

**Comment by philpep** [comment]
I think you can also fix it by adding /sbin and /usr/sbin in your PATH (via `.profile` or `.bashrc`).

What I dislike with the current beharvior is that sudo return an error code 1 instead of 127. Testinfra make a strict verification of exit codes and will raise an error like "Unexpected exit code 127: sudo: service: command not found". Using sudo /bin/sh -c 'COMMAND' seems the better way to handle this properly.

**Comment by mchugh19** [comment]
Thanks all. 

I didn't have any luck with that sh -c command, nor with -E. But was able to get it going with additional quoting:
```
$ ssh hcladmin@evprappbpwl01.domain.name sudo '/bin/sh -c "service nimbus status; echo $?"'
```

Without the wrapping single quotes, sudo just ran the command /bin/sh -c service, where service then only posted usage info.

**Comment by daenney** [comment]
That's actually how `-c` works:

>  -c string If the -c option is present, then commands are read from string.  If there  are  arguments  after  the string, they are assigned to the positional parameters, starting with $0.

The space by default will be interpreted as the end of the string, field separator. So `-c` would only see `service`.

**Comment by philpep** [comment]
Ok thanks. I'll try to reproduce the issue ASAP and make the appropriate fix.

**Comment by philpep** [comment]
Hi @mchugh19 

Can you test #42 and tell me if it's solve your issue ?

```pip install -U 'git+https://github.com/philpep/testinfra@wip-sudo#egg=testinfra'```

NB: Seems the path used with sudo is controled by the `secure_path` parameter. In my patch I use `sudo /bin/sh` so I think the good PATH will come from `/bin/sh`.

**Comment by mchugh19** [comment]
Didn't get to this until the branch was already merged, but it looks good now. 

Thanks!

**Comment by mchugh19** [comment]
I may have spoken too soon. Looks like this corrects the problem for RHEL 6.5, but 5.11 still throws "service: command not found" errors. 

Even manually ssh'ing into RHEL 5, and running sudo service blah status, doesn't work, but running sudo -s; . /etc/profile; service blah status, does. 

I'm not aware of a linux distro (too out of touch to comment on BSD) that provides service in any directory besides /sbin. So I think that hardcoding the path might be a way forward for older RHEL at least.

**Comment by philpep** [comment]
I'm pretty happy with the beharvior right now. At least It will raise an error "Unexpected exit code 127: service: command not found". Hardcoding the path would be ugly (lots of command like service in [...]/sbin). This can be fixed with a proper sudo configuration (secure_path) or with shell configuration.
