### ISSUE TITLE
Wheel for 1.19 changed, breaking installs with locked dependencies

### ISSUE THREAD

**Issue by conorsch** [philpep/testinfra#419]
On 2019-03-25, the wheel for testinfra 1.19 [uploaded to PyPI](https://pypi.org/project/testinfra/1.19.0/#files) changed, but the source tarball did not. 

![testinfra-pypi-wheel](https://user-images.githubusercontent.com/657862/55013382-3ee6f680-4fa6-11e9-863d-c284d3e230b7.png)

The sudden wheel change breaks installs of testinfra if the hashes were pinned, such as in a `requirements.txt` or (for our case) a `Pipfile.lock`. 

Why did this wheel change? The reason Python package managers support version pinning is to alert maintainers that software _other than that_ which was explicitly approved during review is about to be installed. Appropriately, pipenv aborts the installation and complains about the hash mismatch.

If you have the ability to restore the old wheel file, please do, otherwise you may be breaking installs for anyone running 1.19 with pinned dependencies. We caught this in our CI system.

**Comment by conorsch** [comment]
Ah, appears to be related to discussion in https://github.com/philpep/testinfra/issues/417#issuecomment-476139740. @philpep it sounds it was the _re-upload_ of the 1.19 wheel that broke for our use case. Since you've already unjustly been put through the wringer on this one—and furthermore, because I found documentation of the wheel change!—I don't see much more you can do as a maintainer, other than release yet-another-version, with stable wheels.

For our part, we'll investigate moving to v2, since we have to do that anyway!

Many thanks for your hard work on this project, @philpep!

**Comment by philpep** [comment]
Hi,

Yes indeed, we had no weels before and I uploaded them yesterday. Good to known that pipenv doesn't  handle this, maybe it should store couple of release url / hash instead and in your case choose to download the sdist rather than of the wheel.
Since now I'll upload wheel for each release, so this should not occur anymore.

Thanks for reporting, and I'm very proud that securedrop is using testinfra :)

**Comment by webknjaz** [comment]
@conorsch FTR it's impossible to replace dists on PyPI, just so you know.

P.S. Pipenv should be able to hold multiple hashes in its lockfile. So you'd just need to update that.
