### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by knightdave** [philpep/testinfra#442]
Hello,
I wanted to add you package to [conda-forge](https://conda-forge.org/) repository. 

I've prepared everything in [my repo](https://github.com/knightdave/staged-recipes/tree/testinfra) and its ready to [create pull request](https://conda-forge.org/#add_recipe) to conda-forge repo.

I wanted to ask, can I add you to [recipe-maintainers](https://github.com/conda-forge/staged-recipes/blob/4b85c979ad18b5d239e5848759a3c813a4f50a16/recipes/example/meta.yaml#L78). Documentation of conda-forge can be found [here](http://conda-forge.org/docs/user/00_intro.html).

**Comment by philpep** [comment]
Hi, feel free to package testinfra on conda, but I don't want to maintain this because I known nothing about conda.

Cheers,

**Comment by knightdave** [comment]
OK, copy that, no problem. Thanks for the answer :)
