### ISSUE TITLE
Handle all ansible connection types (was New Ansible Connection Backend (network_cli))

### ISSUE THREAD

**Issue by FragmentedPacket** [philpep/testinfra#453]
This is related to the changes in #431. Could network_cli possibly be added back as a connection? It works fine in 2.1.0, but breaks 3.0.X or does this fall in the basket of licensing issues with Ansible?

**Comment by philpep** [comment]
Hi,

What kind of device are you using with network_cli ?
I think we could add support for all ansible connection types that are not covered by testinfra, but this will be slower than with 2.X due to calling ansible in subprocess.

**Comment by FragmentedPacket** [comment]
We're using Cisco IOS-XE (CSR100V), Arista vEOS, vNX-OS, Juniper vMX for testing our Ansible roles for network devices.

That would be great as network device testing is pretty tough with Ansible and typically requires testing directly to a device. I assume we'll be testing using several different connection types (network_cli, httpapi, netconf, etc.)
