### ISSUE TITLE
Using kubeconfig to connect to kubernetes

### ISSUE THREAD

**Issue by shikaan** [philpep/testinfra#459]
Hello,
I was trying to use `kubectl` as host, but I need to use the appropriate kubeconfig file to access the cluster.

I have tried something along the lines of:

```
pytest --host="kubectl://${WEBSERVER}?kubeconfig=.kubeconfig/development" ./tests/test_web_server.py
```

but that did not work, as I am getting

```
E               AssertionError: Unexpected exit code 1 for CommandResult(command=b'kubectl exec *** -- /bin/sh -c \'systeminfo | findstr /B /C:"OS"\'', exit_status=1, stdout=None, stderr=b'The connection to the server localhost:8080 was refused - did you specify the right host or port?\n')
E               assert 1 == 0
E                +  where 1 = CommandResult(command=b'kubectl exec *** -- /bin/sh -c \'systeminfo | findstr /B /C:"OS"\'', exit_sta...ut=None, stderr=b'The connection to the server localhost:8080 was refused - did you specify the right host or port?\n').rc
```

As far as I can tell by this log, that was the wrong query-string option as the `--kubeconfig` options does not appear in the executed command. Unfortunately I did not find anything about that in docs.

Is this feature there?

If yes, can I help with documentation?
If not, can I help with implementation?

Thanks for the great work

**Comment by krepflap** [comment]
Does using KUBECONFIG env var work ?

https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable

**Comment by shikaan** [comment]
Did not try to be honest, but in my case I had suites running concurrently with different `KUBECONFIG`s so I could not make use of it. 

Anyway, I implemented the feature (and I am currently working with my own fork for this ^ case) in the referenced pull request

**Comment by shikaan** [comment]
This is closed by https://github.com/philpep/testinfra/pull/460
