### ISSUE TITLE
get_ansible_inventory: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ssbarnea** [philpep/testinfra#470]
Location of issue https://github.com/philpep/testinfra/blob/master/testinfra/utils/ansible_runner.py#L58

In order to unblock current users we need to implement a workaround in testinfra: disabling ansible verbosity for this command via `ANSIBLE_VERBOSITY=0`.

Upstream bug: https://github.com/ansible/ansible/issues/59973
Downstram bug: https://github.com/ansible/molecule/issues/2188

**Comment by ssbarnea** [comment]
@philpep @ianw Can you please check the the two proposed PR for fixing this bug? Any would them would be ok, I do not care much which but I need a new patch release for molecule.

**Comment by decentral1se** [comment]
Solid detective work. I prefer https://github.com/philpep/testinfra/pull/471 and have left a review.
