### ISSUE TITLE
compatibility issue with Molecule and delegated driver

### ISSUE THREAD

**Issue by javierjimsa** [philpep/testinfra#474]
From Testinfra 3.0 and onwards is no possible to execute tests with molecule (tested from molecule 2.19.0) since `testinfra/utils/ansible_runner.py` does not recognize the connection type "smart" which is the default for ansible as stated here:
[https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#](url)

When the molecule delegated driver compiles the ansible inventory it takes the ssh connection as smart.

`    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    ../../.venv/lib/python3.7/site-packages/testinfra/host.py:107: in __getattr__
        obj = module_class.get_module(self)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/base.py:22: in get_module
        klass = cls.get_module_class(_host)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/file.py:187: in get_module_class
        if host.system_info.type == "linux":
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:143: in type
        return self.sysinfo["type"]
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/__init__.py:44: in __get__
        value = obj.__dict__[self.func.__name__] = self.func(obj)
    ../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:33: in sysinfo
        uname = self.run_expect([0, 1], 'uname -s')
    ../../.venv/lib/python3.7/site-packages/testinfra/host.py:71: in run
        return self.backend.run(command, *args, **kwargs)
    ../../.venv/lib/python3.7/site-packages/testinfra/backend/ansible.py:46: in run
        ssh_identity_file=self.ssh_identity_file)
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:183: in run
        return self.get_host(host, **kwargs).run(command)
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:179: in get_host
        self.ansible_config, self.inventory, host, **kwargs)
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:107: in get_ansible_host
        return testinfra.get_host(spec, **kwargs)
    ../../.venv/lib/python3.7/site-packages/testinfra/host.py:132: in get_host
        backend = testinfra.backend.get_backend(hostspec, **kwargs)
    ../../.venv/lib/python3.7/site-packages/testinfra/backend/__init__.py:73: in get_backend
        klass = get_backend_class(kw["connection"])
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    connection = 'smart'
    
        def get_backend_class(connection):
            try:
                classpath = BACKENDS[connection]
            except KeyError:
    >           raise RuntimeError("Unknown connection type '%s'" % (connection,))
    E           RuntimeError: Unknown connection type 'smart'
    
    ../../.venv/lib/python3.7/site-packages/testinfra/backend/__init__.py:39: RuntimeError
    _ test_httpd_is_installed[ansible://ansible-role-proto_featuremolecule_testing.mrd.roche.com] _
    [gw0] linux -- Python 3.7.3 /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/feature_molecule_testing_242/.venv/bin/python3
    
    host = <testinfra.host.Host object at 0x7f15403fcbe0>
'

It works with previous versions of testinfra like 2.1.0

**Comment by philpep** [comment]
hi, what version of ansible are you using ?

**Comment by javierjimsa** [comment]
> hi, what version of ansible and testinfra are you using ?

I have tested with ansible 2.6 onwards until 2.8 but right now I am using ansible 2.7.11 and testinfra 2.1.0 which is working. But if I upgrade testinfra to 3.0 or superior the error appears again.

**Comment by javierjimsa** [comment]
Hi again @philpep, tested again with ansible 2.8.3 and testinfra 3.0.6 with python 3.7.3. Same results:

 def get_ansible_host(config, inventory, host, ssh_config=None,
                             ssh_identity_file=None):
            if is_empty_inventory(inventory):
                return testinfra.get_host('local://')
            hostvars = inventory['_meta'].get('hostvars', {}).get(host, {})
            connection = hostvars.get('ansible_connection', 'ssh')
            if connection not in ('ssh', 'local', 'docker', 'lxc', 'lxd'):
                raise NotImplementedError(
    >               'unhandled ansible_connection {}'.format(connection))
    E           NotImplementedError: unhandled ansible_connection smart
    
    ../../.venv/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:71: NotImplementedError

it seems that "smart" is not under implemented ssh connections, but molecule and ansible use it by default. See [#2199](https://github.com/ansible/molecule/issues/2199)
