### ISSUE TITLE
"force_ansible=True" fails when "lsb_release" executable isn't available

### ISSUE THREAD

**Issue by pilou-** [philpep/testinfra#481]
Because [`AnsibleRunner.run_module` uses `run_execpt`](https://github.com/philpep/testinfra/blob/b1e369d9d440931553aebf68872ff08cc21ca0ba/testinfra/utils/ansible_runner.py#L206), there is an [uncatched exception](https://github.com/philpep/testinfra/blob/b1e369d9d440931553aebf68872ff08cc21ca0ba/testinfra/modules/systeminfo.py#L54) when `lsb_release` executable isn't available on managed host. Then `/etc/os-release` isn't read and this failure occurs.

Backtrace:
```
>        inventory = os.environ['MOLECULE_INVENTORY_FILE']
>        uri = 'ansible://%s?ansible_inventory=%s&force_ansible=True'
>        my_host = testinfra.get_host(uri % ('test_host', inventory))
>        my_file = my_host.file("/path/to/file")

molecule/resources/tests/test_custom.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/host.py:107: in __getattr__
    obj = module_class.get_module(self)
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/modules/base.py:22: in get_module
    klass = cls.get_module_class(_host)
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/modules/file.py:187: in get_module_class
    if host.system_info.type == "linux":
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:143: in type
    return self.sysinfo["type"]
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/utils/__init__.py:44: in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:40: in sysinfo
    sysinfo.update(**self._get_linux_sysinfo())
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/modules/systeminfo.py:54: in _get_linux_sysinfo
    lsb = self.run("lsb_release -a")
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/host.py:71: in run
    return self.backend.run(command, *args, **kwargs)
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/backend/ansible.py:52: in run
    out = self.run_ansible('shell', module_args=command, check=False)
/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/backend/ansible.py:60: in run_ansible
    **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <testinfra.utils.ansible_runner.AnsibleRunner object at 0x7f2d3843c7d0>, host = 'application', module_name = 'shell', module_args = 'lsb_release -a', become = False
check = False, kwargs = {}, cmd = 'ansible --tree %s -i %s -m %s --args %s %s'
args = ['/tmp/tmpwjcf8pt9', '/tmp/molecule/testproject/default/inventory/ansible_inventory.yml', 'shell', 'lsb_release -a', 'application'], d = '/tmp/tmpwjcf8pt9'

    def run_module(self, host, module_name, module_args, become=False,
                   check=True, **kwargs):
        cmd, args = 'ansible --tree %s', [None]
        if self.inventory_file:
            cmd += ' -i %s'
            args += [self.inventory_file]
        cmd += ' -m %s'
        args += [module_name]
        if module_args:
            cmd += ' --args %s'
            args += [module_args]
        if become:
            cmd += ' --become'
        if check:
            cmd += ' --check'
        cmd += ' %s'
        args += [host]
        with TemporaryDirectory() as d:
            args[0] = d
>           out = local.run_expect([0, 2], cmd, *args)
E           AssertionError: Unexpected exit code 8 for CommandResult(command=b"ansible --tree /tmp/tmpwjcf8pt9 -i /tmp/molecule/testproject/default/inventory/ansible_inventory.yml -m shell --args 'lsb_release -a' application", exit_status=8, stdout=b'application | FAILED | rc=127 >>\n/bin/sh: 1: lsb_release: not foundnon-zero return code\n', stderr=None)
E           assert 8 in [0, 2]
E            +  where 8 = CommandResult(command=b"ansible --tree /tmp/tmpwjcf8pt9 -i /tmp/molecule/testproject/default/inventory/ansible_inven...s=8, stdout=b'application | FAILED | rc=127 >>\n/bin/sh: 1: lsb_release: not foundnon-zero return code\n', stderr=None).rc

/tmp/molecule-test-py3/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:206: AssertionError
```

**Comment by ianw** [comment]
Is this something that can only happen on redhat systems, as the lsb bits are optional (I think it's basically always installed on debian systems?)

could possibly fallback to something like https://github.com/philpep/testinfra/pull/248 ?

**Comment by pilou-** [comment]
`debian:stretch` / `debian:buster` docker images doesn't provide `lsb_release` executable but `/etc/os-release` is available.

[AnsibleRunner.run_module excepts](
https://github.com/philpep/testinfra/blob/b1e369d9d440931553aebf68872ff08cc21ca0ba/testinfra/utils/ansible_runner.py#L206) ansible returns `0` or `2`, but [other values can be returned](https://github.com/ansible/ansible/blob/523e40e993c06a6c15234c9a3c951b5398e44184/lib/ansible/executor/task_queue_manager.py#L63-L68). For example when `ANSIBLE_ANY_ERRORS_FATAL` is defined and an error occurs, `8` is returned.

When molecule is used, instead of enabling `ANY_ERRORS_FATAL` with an environment variable:
```
provisioner:
  name: ansible
  env:
    ANSIBLE_ANY_ERRORS_FATAL: 'true'
```
using `config_options` allows to workaround this issue:
```
provisioner:
  name: ansible
  config_options:
    any_errors_fatal: True
```

Since only `0` and `2` are supported by testinfra, should `ANSIBLE_ANY_ERRORS_FATAL=false` be defined by testinfra when ansible executable is used ?

**Comment by philpep** [comment]
Thanks for reporting, and many thanks for doing this just before I plan to release the next version introducing "force_ansible=True" ! :)

Yes, seems the issue occur only when ANSIBLE_ANY_ERRORS_FATAL is set to True. And either @pilou- suggestion to set ANSIBLE_ANY_ERRORS_FATAL to False in testinfra or adding ``8`` as the expected code should fix this.

**Comment by philpep** [comment]
Since I don't known about side effect of setting ANSIBLE_ANY_ERRORS_FATAL explicitly to False. I'll go for accepting 8 as expected exit code for ansible call.

**Comment by amarao** [comment]
Sorry to writing in a closed issue. Where `force_ansible` should go in case of command line invocation? I see it in tests with 'uri' type of calls, but I can't find any command line option for that.

```
py.test  --ansible-inventory=inventory --connection=ansible   test_one.py
```

and there is nothing about force_ansible in `py.test --help` output..

**Comment by philpep** [comment]
@amarao this is documented here https://testinfra.readthedocs.io/en/latest/backends.html#ansible

``py.test --ansible-inventory=inventory --hosts "ansible://all?force_ansible=True"``. Maybe we could add a ``--force-ansible`` flag to the command line.

**Comment by amarao** [comment]
Oh! Thanks.

--force-ansible would be really good.

Currently there is a bit of confusion about this. It took me a bit of time to realize that pytest uses own ssh instead of ansible to connect to hosts.
