### ISSUE TITLE
Error when executed with Molecule and delegated driver

### ISSUE THREAD

**Issue by javierjimsa** [philpep/testinfra#486]
Ansible 2.7.11
Molecule 2.22
Testinfra 3.1.0

When executed pytest with molecule verify command, the following error appears:

_ValueError: unsupported format character '-' (0x2d) at index 164_

'''
host = <testinfra.host.Host object at 0x7f3bfd62eac8>
    
    [1m    def test_passwd_file(host):[0m
    [1m>       passwd = host.file("/etc/passwd")[0m
    
    [1m[31m../../tests/test_httpd.py[0m:12:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/host.py[0m:107: in __getattr__
    [1m    obj = module_class.get_module(self)[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/modules/base.py[0m:22: in get_module
    [1m    klass = cls.get_module_class(_host)[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/modules/file.py[0m:187: in get_module_class
    [1m    if host.system_info.type == "linux":[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py[0m:143: in type
    [1m    return self.sysinfo["type"][0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/utils/__init__.py[0m:44: in __get__
    [1m    value = obj.__dict__[self.func.__name__] = self.func(obj)[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/modules/systeminfo.py[0m:33: in sysinfo
    [1m    uname = self.run_expect([0, 1], 'uname -s')[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/host.py[0m:71: in run
    [1m    return self.backend.run(command, *args, **kwargs)[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/backend/ansible.py[0m:51: in run
    [1m    return host.run(command)[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/host.py[0m:71: in run
    [1m    return self.backend.run(command, *args, **kwargs)[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/backend/ssh.py[0m:37: in run
    [1m    return self.run_ssh(self.get_command(command, *args))[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/backend/ssh.py[0m:67: in run_ssh
    [1m    " ".join(cmd), *cmd_args)[0m
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/backend/base.py[0m:195: in run_local
    [1m    command = self.quote(command, *args)[0m
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    command = 'ssh -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKe...ansible/cp/%r@%h-%p -o User=%s -o Port=%s -i %s -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPersist=60s %s %s'
    args = (****, '22', '/var/lib/jenkins/.cache/molecule/feature_molecule_testing_273/vmware/ssh_key', '10.120.52.19', "sudo /bin/sh -c 'uname -s'")
    
    [1m    @staticmethod[0m
    [1m    def quote(command, *args):[0m
    [1m        if args:[0m
    [1m>           return command % tuple(pipes.quote(a) for a in args)[0m
    [1m[31mE           ValueError: unsupported format character '-' (0x2d) at index 164[0m
    
    [1m[31m../../.venv/lib/python3.7/site-packages/testinfra/backend/base.py[0m:176: ValueError
    [31m[1m_ test_httpd_is_installed[ansible://protofeaturemoleculetesting.mrd.roche.com] _[0m
    [gw0] linux -- Python 3.7.3 /var/lib/jenkins/workspace/e-proto_feature_molecule_testing@2/feature_molecule_testing_273/.venv/bin/python3

'''

**Comment by philpep** [comment]
Hi, thanks for reporting.
I think this is a shell escape issue related to ansible ssh_extra_args.
