### ISSUE TITLE
support ansible 2.x 

### ISSUE THREAD

**Issue by binarytemple** [philpep/testinfra#49]
In Ansible 2.x the Python API has changed, the relevant docs are [here](https://github.com/ansible/ansible/blob/d9d4ad828a7d3f9f1440e4bec7150756165b754b/docsite/rst/developing_api.rst). 

A check is made in [L21-27 of ansible.py](https://github.com/philpep/testinfra/blob/master/testinfra/backend/ansible.py#L21-L27) to try and import `ansible.runner` and an variable `HAS_ANSIBLE` is set to True or False as a result.

```
try:
    import ansible.inventory
    import ansible.runner
except ImportError:
    HAS_ANSIBLE = False
else:
    HAS_ANSIBLE = True
```
The module `ansible.runner` has been removed from Ansible 2.x (a PITA I know).

[Later](https://github.com/philpep/testinfra/blob/master/testinfra/backend/ansible.py#L42-L46) a check is made on this variable, if it is set to False the program bails out with an error 'You must install ansible package to use the ansible backend'.

**Comment by philpep** [comment]
Hi, indeed testinfra isn't compatible with ansible 2.0.

I'm a bit afraid by the API v2 example on https://docs.ansible.com/ansible/developing_api.html#python-api-2-0 (compared to the v1 example)...

**Comment by binarytemple** [comment]
Yeah... it's hideous... otherwise I would have just hacked a P/R together ;-) Second system syndrome at it's worst..

**Comment by philpep** [comment]
Some code for inspiration: https://github.com/seantis/suitable

Also we need to support both ansible 1.X and ansible 2.X

**Comment by binarytemple** [comment]
I've got about 70% of the way towards getting it working with Ansible 1 and 2 - I'm not very familiar with how the testinfra code is structured though or Ansible internals. 

* Created one [commit](https://github.com/packetops/testinfra/commit/5ab40de58df8ff15cd3a131b016b622c70389cb1)

* My copy of the file (master branch) [here](https://github.com/packetops/testinfra/blob/master/testinfra/backend/ansible.py)

I'm getting stuck at figuring out the invocation stuff, and what data structures testinfra expects to see. I've run out of time now for the rest of the week as I'm on a tight deadline. Let me know what you think. I've been testing using virtualenv and manually installing/uninstalling Ansible using pip - on a molecule project like so:

```
testinfra --connection=ansible --sudo \
--ansible-inventory=.molecule/ansible_inventory --ignore=venv
```
Let me know if you'd like any more info, I'll try to hack away next week as well but time is very short at the moment. 

Bryan

**Comment by philpep** [comment]
Hi nice work !! I was working on it too with a sample code: https://gist.github.com/philpep/a777410a10766e5a9d39

So It seems that we must use the `connection = "smart"` in `Option` and create a callback class (one more :D) to get the results.

I think I can finish this work and integrate in a few days.

My idea is to create a compatibility module that handle v1 and v2 API and just expose `get_hosts()` and `run()`.

**Comment by binarytemple** [comment]
It's shit ugly but the code I hacked is working now. You may want to refactor but hopefully it's some use to you even in it's current state. 

https://github.com/packetops/testinfra/blob/master/testinfra/backend/ansible.py

Feel free to use it as you please.

**Comment by philpep** [comment]
I'm stuck on this bug: https://github.com/ansible/ansible/issues/13862

Workaround example: https://github.com/seantis/suitable/commit/ac27e02872f977b03002f43d73c21bbdd400f117

**Comment by philpep** [comment]
@binarytemple I've working code in #50 that you can test.

**Comment by binarytemple** [comment]
Sorry @philpep  - I've got to get https://github.com/packetops/ansible-etcd up and working today. If I get any time this weekend I'll take a look. B
