### ISSUE TITLE
Exact match pattern on file.contains module

### ISSUE THREAD

**Issue by k4ch0** [philpep/testinfra#500]
Hi team,

Molecule version: 2.20.1
Testinfra version: 1.19.0

I'm trying the next test using molecule:

```
def test_modprobe(host, ansible_variables):
    dict_variables = converttostr(ansible_variables)
    dict_fs = dict_variables['disabled_filesystems_ubuntu18_04']

    for value in dict_fs.values():
        f = host.file('/etc/modprobe.d/'+str(value)+'.conf')
        assert f.exists
        assert f.user == 'root'
        assert f.group == 'root'
        assert f.contains('install '+str(value)+' /bin/true')
 ```
I'm looking for a line like: ```install cramfs /bin/true``` but it should failed if the line have anything else on the same line for example:```install cramfs /bin/true extrainfo```.
Not saying that it should exists an extra info on the file, but I just want to match the exact pattern and avoid any other data on the same line.

Any help is welcome

**Comment by philpep** [comment]
Hi, I think you can do this with `contains('^install cramfs /bin/true$')`. Under the hood testinfra use `grep -qs -- <pattern> <filename>` and grep work with regexes.
