### ISSUE TITLE
Add manjaro linux support

### ISSUE THREAD

**Issue by Insolita** [philpep/testinfra#503]
it same as an archlinux, but host.system_info.distribution  is manjarolinux instead of arch

**Comment by philpep** [comment]
Hi, I think this has to be fixed in manjarolinux. testinfra looks for distribution using lsb_release or /etc/os-release, it belong to the distribution to put correct information here.

**Comment by hurricanehrndz** [comment]
@philpep 

Manjaro does the same thing Ubuntu does for os-release, the package manager should be determined by os family rather than distribution. ID_LIKE should be the variable used rather than ID.
