### ISSUE TITLE
Using ansible inventory without using ansible backend

### ISSUE THREAD

**Issue by jorisroovers** [philpep/testinfra#51]
This is a feature request.

I'd like to be able to use a (dynamic) ansible inventory in combination with ```--hosts``` to determine the target hosts, but just use an ssh connection instead of the ansible connection backend to actually perform the tests against the target hosts (mainly because performing the tests using ansible is much, much slower). 

A more generic solution to this would be the ability to specify a custom generic *.py file that provides the hosts to test_infra (the --hosts parameter would be passed to this file). This way, everyone can write their own integrations (very similar to how ansible does it).

**Comment by philpep** [comment]
I think you can already do it ;)

```
$ cat > inventory.sh << EOF
echo "localhost,root@server:2222"
EOF
$ chmod +x inventory.sh
$ testinfra --hosts=$(./inventory.sh)
```

There are several way to accelerate ansible, maybe they don't all applies to testinfra use case, but mine works fine, I've this in my `ansible.cfg` (persistent ssh connection):

```
[defaults]
transport=ssh

[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=~/.ssh/ansible-ssh-%h-%p-%r
pipelining=True
```
