### ISSUE TITLE
Ansible remote_user

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#53]
testinfra  -v --connection=ansible --ansible-inventory=inventories/ec2.py --hosts=key_Release001  main.py

The command above seems to work except 
1/ My entire inventory is dynamic
2/ SSH agent configuration is working and tested
3/ How can I specify the user to ssh on the remote box?
In my ansible setup, I do it with a directive in the playbook (remote_user). My local user is emayssat, my remote user is ubuntu.

Maybe should I use ansible.cfg? Other?

**Comment by emayssat-ms** [comment]
http://docs.ansible.com/ansible/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script

https://aws.amazon.com/blogs/apn/getting-started-with-ansible-and-dynamic-amazon-ec2-inventory-management/ 

   just in case! ;-)

**Comment by philpep** [comment]
Hi,

I see two solutions that you could try:

- have your inventory return `ansible_user` (ansible 2.X) or `ansible_ssh_user` (ansible 1.X).
- Add remote_user=ubuntu in your ansible.cfg

**Comment by emayssat-ms** [comment]
I don't have control of the inventory script.
I tried the ansible.cfg solution and it works like a charm.
Thank you.
Emmanuel
