### ISSUE TITLE
Where does TestinfraDeprecationWarning comes from?

### ISSUE THREAD

**Issue by ssbarnea** [philpep/testinfra#531]
I recently encounted some annoying deprecation warnings which I did not see before:

```
platform darwin -- Python 2.7.16, pytest-4.6.9, py-1.8.1, pluggy-0.13.1 -- /Users/ssbarnea/c/os/molecule/.tox/py27-ansible28-unit/bin/python
cachedir: .tox/py27-ansible28-unit/.pytest_cache
metadata: {'CI': '1', 'Packages': {'pluggy': '0.13.1', 'pytest': '4.6.9', 'py': '1.8.1'}, 'JAVA_HOME': '/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home', 'Plugins': {u'helpers-namespace': u'2019.1.8', u'mock': u'1.13.0', u'testinfra': u'3.4.0', u'xdist': u'1.31.0', u'verbose-parametrize': u'1.7.0', u'cov': u'2.8.1', u'html': u'1.22.1', u'metadata': u'1.8.0', u'forked': u'1.1.3'}, 'Python': '2.7.16', 'Platform': 'Darwin-19.2.0-x86_64-i386-64bit'}
rootdir: /Users/ssbarnea/c/os/molecule, inifile: setup.cfg
plugins: testinfra-3.4.0, helpers-namespace-2019.1.8, mock-1.13.0, xdist-1.31.0, verbose-parametrize-1.7.0, html-1.22.1, forked-1.1.3, metadata-1.8.0, cov-2.8.1

/molecule/.tox/py27-ansible28-unit/lib/python2.7/site-packages/testinfra/__init__.py:32: TestinfraDeprecationWarning: DEPRECATION: testinfra python2 support is unmaintained, please upgrade to python3
```

The most interesting part is that I search this repository for occurrence of TestinfraDeprecationWarning and there is none, in the code, issues or PRs.

That is a serious reason to be warned because it means that the code released on pypi is not the code from the repository. Or github search got broken, which is unlikely.

**Comment by philpep** [comment]
Hi @ssbarnea ,

This come from https://github.com/philpep/testinfra/commit/df038a485a2aaf80bcfbd872e94ffb87bcb5b33c which is dropped in 4.0.0 where py2 support has been dropped.

I think it's better to inform users that they run a version of testinfra which will no longer receive updates.

**Comment by ssbarnea** [comment]
Sadly I cannot drop py27 support out of molecule so I am faced with a conundrum. Options that I see:

- find a way to disable thar warning in pytest.ini
- drop support for testinfra in molecule when running on py27 (would also speed-up testing) but this would be another breaking change to add to the current v3 pre-release.
- make testinfra a plugin so I no longer test it in molecule, the plan was to only make it non default verifier, not to externalize it, at least not now.
- remove the warning

TBH, that warnings joins the PIP deprecation ones, which made me, and others, really hate those tools. Nobody likes being forced-fed advertising, even if is with good intentions. For CI usage these kind of warnings are mostly noise and if think about big picture where every dependency is adding it you can imagine how frustrating is for someone running one or two tests to have scroll back for days to see the outcome if his own test.

Any ideas on how to proceed?

**Comment by philpep** [comment]
Well I not fully agree with you. But I understand a "warnings.warn" is not the best choice for this kind of message.
Here's what we can do: fork from tag 3.4.0, revert df038a4 and tag 3.4.1. I think you can do it by yourself, since you have commit bit, and travis should release this to pypi :)

**Comment by ssbarnea** [comment]
Thanks. If I run out of more urgent of things to fix I will do something about it. Getting comments from others will probably be a way to persuade me to do it.
