### ISSUE TITLE
document way to write tests that avoid breaking pytest collection

### ISSUE THREAD

**Issue by ssbarnea** [philpep/testinfra#535]
On molecule we have a cookiecutter template for using testinfra as verifier as seen at https://github.com/ansible-community/molecule/blob/master/molecule/cookiecutter/scenario/verifier/testinfra/%7B%7Bcookiecutter.molecule_directory%7D%7D/%7B%7Bcookiecutter.scenario_name%7D%7D/%7B%7Bcookiecutter.verifier_directory%7D%7D/test_default.py 

In its current form it can break pytest ability to collect tests for two reasons: either testinfra is not installed or the test is called from outside molecule, where the variable is not defined, giving an exception.

I would like to change the template in such way that testinfra tests are skipped (or xfailed) when any of these two requirements are not met, avoiding breakind pytest collection. Main reason for this is that we often use pytest with other kind of tests and we do not want to overcomplicate executions with include and exclude scenarios. Mainly adding a new testinfra backed test to a role should not break another testing job.

I do have a PR that seems to be working at https://github.com/ansible-community/molecule/pull/2555/files but  it would be nice to have a confirmation if what is done there is correct or not.

**Comment by philpep** [comment]
The approach looks correct to me, altrough I'm not sure what the difference of having this in setup hook instead of module level. I guess this make the file python importable for linters without side effect which seems a good idea...
