### ISSUE TITLE
Is this tool used in production if so in which environment? Alpha release

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#54]
Hello,

As a python aficionado, I am seriously considering using testinfra to test my production Ansible/AWS deployments. I noticed that the latest version of testinfra is an alpha release. What does that mean?

I understand to date you only support linux platforms and not Windows nor OS X.
Not a problem for us as we run everything on linux (ubuntu 14.04 at the moment).

Input/advice appreciated.
Best,
--
Emmanuel

**Comment by philpep** [comment]
Hi,

Testinfra 1.0.0 is planned soon, so you can already consider that the documented API for modules will be backward compatible.

My plan are to close #52 and make the first release.

**Comment by philpep** [comment]
Hi,

1.0.0 released today
