### ISSUE TITLE
host.run("java -version") send output to stderr instead of stdout

### ISSUE THREAD

**Issue by deamicis** [philpep/testinfra#542]
Hi,
I have a simple test for checking and parsing the output of `java -version`. I spent couple of minutes in figuring out why the stdout was always empty and then I've noticed that the output was sent to stderr.
The test is running against an Ubuntu server 16.04.6 LTS
Simple Test:
```
def test_installed_java_package_is_in_use(host):
    "Check that installed Java (OpenJDK) 8 is in use"
    java_version_out = host.run("java -version").stdout
    java_version_err = host.run("java -version").stderr
    print("stdout\n"+java_version_out)
    print("stderr\n"+java_version_err)
```
Test Output:
```
stdout
<<nothing here>>
stderr
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
As you can see the stdout is empty but stderr contains the output. Not sure if it's a bug in testinfra or in how java print the output. Any advice?

Thank You

**Comment by nmusatti** [comment]
It's java:
[nick@imladris tmp]$ java -version > out 2> err
[nick@imladris tmp]$ cat out
[nick@imladris tmp]$ cat err
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by deamicis** [comment]
Yep. noticed..
