### ISSUE TITLE
AWS and multiple acounts

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#55]
To build my inventory on ansible, I use 

AWS_PROFILE='my_aws_profile' ansible -i inventories/ec2.py .....

To deploy on another AWS account, I simply change the AWS_PROFILE variable.
Now, does your ansible backend recognize environment variables?
At the present time, it doesn't seem to be the case.
In other words, your solution works only for the default AWS account.

Regards,
--
Emmanuel

**Comment by philpep** [comment]
Testinfra use ansible API to get hosts from inventory, so that should work.

Is this command return the correct inventory ?

``AWS_PROFILE='my_aws_profile' python -c 'from testinfra.utils.ansible_runner import get_hosts; get_hosts("inventories/ec2.py")'```

**Comment by emayssat-ms** [comment]
After investigation your software behave as ansible does.
It turns out ec2.py can create several cache profiles (one per account), but because of the way it is invoked with ansible, it is using the same cache (a third one if you have 2 accounts/cache profiles) which is the no-profile one. If your cache policy is 5 minutes, you will not notice this if you work with an account one day and another the following day. But if you switch back and forth, several times an hour you will. (as I did!). Maybe a solution is to use 2 wrapper scripts around ec2.py (which would call respectively ec2.py with the hardcoded AWS profiles). I send an email to the ansible google group to see if there is a better solution. In any case, your software behave like ansible does. Thanks,

**Comment by emayssat-ms** [comment]
https://groups.google.com/forum/?fromgroups#!topic/ansible-project/pcHSVgc2JG8
