### ISSUE TITLE
keywords and extra_keyword_matches set

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#57]
I like the -k argument for testinfra.
I can run test based on the name of the test.
Nevertheless, I would like to be able to filter-out or select tests based on something else than the test name. It seems that the extra_keyword_matches is what I want.
Unfortunately, there is no doc on this.
Info in the docs would be appreciated instead of having to look at the source.

Best,

**Comment by emayssat-ms** [comment]
Likewise for 'markers'... which seem to be a feature inherited from pytest.

**Comment by emayssat-ms** [comment]
Maybe a couple of example and a link to this page would help new comers.
http://pytest.org/latest/example/markers.html

I assume everything that is written about pytest is true for testinfra.

**Comment by philpep** [comment]
Hi, indeed testinfra is written as a pytest plugin. The command `testinfra` itself is equivalent to `py.test` (except with `--nagios`).

There are already links and hint to pytest in the documentation:

- https://testinfra.readthedocs.org/en/latest/support.html#pytest-documentation
- https://testinfra.readthedocs.org/en/latest/examples.html#parametrize-your-tests

But I'd like to add more useful examples in testinfra documentation (conftest.py file, hooks, setup/teardown ect)
