### ISSUE TITLE
Escape question

### ISSUE THREAD

**Issue by chazzly** [philpep/testinfra#573]
I'm not sure if this is the best place for this question or not, but here goes.

I'm Using Ansible, Molecule, and testinfra to test a role I'm working on.  One of the tests I want to run is if a file was correctly updated to contain the text "@\H" (at symbol, backslash, H).  I can't seem to find the correct way to escape this sequence.

I've tried variations of single and double quotes, and single and double backslashes:
```
assert f.contains('@\\H')
assert f.contains('@\H')
assert f.contains("@\\H")
assert f.contains("@\H")
```

In all cases, the test fails and I get 
```
    E       AssertionError: assert False
    E        +  where False = <bound method GNUFile.contains of <file /etc/skel/.bashrc>>('@\\H')
```

Note that in all cases, the error message shows ('@\\\H') - single quotes, double backslash.

I know the playbook works correctly, as I've tried it on test hosts outside of molecule, I simply can't seem to get the test to check for this string correctly.

Any help would be appreciated, thanks.

**Comment by philpep** [comment]
Hi, on linux testinfra use `grep` for `contains()`. In grep the backslash need to be escaped, so `@\\H` but python strings also interpret backslash, to avoid this you can use the raw string prefix `r`.

So ``assert f.contains(r'@\\H')`` should work.

Note for complex cases and when data is not too big you can transfer the whole file and check with python: ``assert rb'@\H' in f.content`` (here we use both raw and bytes prefix).

**Comment by chazzly** [comment]
Thanks, worked perfectly.
