### ISSUE TITLE
Not getting proper running state of service

### ISSUE THREAD

**Issue by msemanicky** [philpep/testinfra#576]
why exit status 1 and 3 are indicating that the service is running ?
https://github.com/philpep/testinfra/blob/cd485d4360f13bbddfc7848576c874f585cbfa32/testinfra/modules/service.py#L105

**Comment by philpep** [comment]
Hi,

Check the next line. We report the service as running only if exit code (`rc`) is zéro.
If exit code is 1, 3 or 8 we report the service as non running.
Other exit codes raises an unexpected exception (that's what `run_expect` does).
