### ISSUE TITLE
unrecognized arguments from py.test's configuration files

### ISSUE THREAD

**Issue by ISF** [philpep/testinfra#59]
I have a `pytest.ini` file that defines additional arguments to be passed to [pytest-ansible](https://pypi.python.org/pypi/pytest-ansible). It makes `testinfra` crash with the following output:

```
% testinfra -p no:pytest-ansible --connection=ansible --sudo --ansible-inventory=inventory --hosts=dev-proxy test_proxy.py
usage: testinfra [options] [file_or_dir] [file_or_dir] [...]
testinfra: error: unrecognized arguments: --ansible-host-pattern test_proxy.py
  inifile: /home/ivan/cde/devops/ansible/pytest.ini
  rootdir: /home/ivan/cde/devops/ansible
```

Contents of `pytest.ini`:
```
[pytest]
addopts = --ansible-host-pattern localhost
```

My current workaround is to move the `pytest.ini` file before running `testinfra` with `-no:pytest-ansible`.

**Comment by philpep** [comment]
Dupplicate #58
