### ISSUE TITLE
Add a marker to filer by ansible host pattern

### ISSUE THREAD

**Issue by FlxPeters** [philpep/testinfra#60]
Hi,

is there a possibility to filter ansible hosts by host pattern? I know the way to filter by name via `--hosts=web*`, but this doesn't work for groups in ansible, only for hostnames. For example I can run a ad hoc command like `ansible -m ping -i inventory groupname` to just contact hosts in the group. This is a pretty cool feature of ansible.

Something like this would be great:  https://github.com/jlaska/pytest-ansible#parameterizing-with-pytestmarkansible. A marker to limit a test to a specific host pattern. So you can have a big test suite, but apply a test for mysql stuff on database hosts only. 

What do you think, is this possible? Maybe even now and I don't get it?

**Comment by philpep** [comment]
Hi,

You can use `--hosts=groupname`, this will target all host in the group `groupname`. To target hosts on a per test basis an issue is already opened #48 (workaround available).
