### ISSUE TITLE
Possibility to load facts from external group_var files 

### ISSUE THREAD

**Issue by doertedev** [philpep/testinfra#61]
OHAI.
I have the current setup:a

``` yml
* code #guess what
* code/playbooks #again, guess what.
* code/playbooks/group_vars/all # file I need facts from in my test cases
* code/tests # guess again
```

I use the following command to run my tests:

`testinfra --connection ansible -n 5 --ssh-config ~/.ssh/config --ansible-inventory tests/hosts.txt`

Now in one of my test cases I need a value of these group_vars file. It's rather large. And using ConfigParser to somehow get it's contents when really it's just ansible facts sounds wrong. Can this facts in there be somehow available from `Ansible('setup')['ansible_facts']` ?

Thanks in advance, this thing really helps!

**Comment by philpep** [comment]
Hi,

First you don't need `--ssh-config ~/.ssh/config` I think.

Then I found a dirty workaround, suppose you have a `myvar` variable defined in host_vars or group_vars (they are automatically loaded by ansible).

```
def test_myvar(Ansible):
    myvar = Ansible("debug", "msg={{ myvar }}")["msg"]
    assert myvar == "myvalue"
```
