### ISSUE TITLE
Load Ansible inventory relative to a test

### ISSUE THREAD

**Issue by FlxPeters** [philpep/testinfra#62]
Hi,

is it possible to specify a inventory file relative to some tests?

For example i have the following structure:
```
├── hosts
│   ├── databases
│   │   ├── inventory.ini
│   │   ├── mysql_test.py
│   └── webservers
│       ├── apache_test.py
│       ├── inventory.ini
```

I can run tests for a specific directory by using `testinfra --connection=ansible --ansible-inventory hosts/webservers/inventory hosts/webservers`. Thats fine.

But i want to run tests on all directories in one run. So it would be great if the inventory would be detected relative to the test files. So i would just call `testinfra --connection=ansible hosts`

I tried around with relative parameters, but i can not get it working:
`testinfra --connection=ansible --ansible-inventory inventory.ini` 

I always get this error report, which seams to be the error when no inventory file is found.:
````
[gw0] darwin -- Python 2.7.10 /usr/bin/python
testinfra_backend = <object object at 0x1046ad0d0>

    @pytest.fixture(scope="module")
    def f(testinfra_backend):
>       return testinfra_backend.get_module(cls.__name__)
E       AttributeError: 'object' object has no attribute 'get_module'

/Library/Python/2.7/site-packages/testinfra/modules/base.py:77: AttributeError
```

Maybe there is a possibility to do it via an ansible.cfg, a marker or a special notation in the --ansible-inventory switch, or something like this?

Hope you have some ideas on this. 

Ps: Great Lib, i really love it!

**Comment by philpep** [comment]
You can try to put this code on top or your tests files:

```
import os

testinfra_hosts = ["ansible://all?ansible_inventory=" + os.path.join(os.path.dirname(os.path.abspath(__file__)), "inventory.ini")]
```

Define `testinfra_hosts` is a way to target host on a per test file basis.

The syntax with `connection-type://host?param1=value1&param2=value2` is undocumented yet, but this is a way to setup connection, sudo, ansible inventory and other params per host (or host pattern). The same syntax applies to `--hosts` option too.

Then just run `testinfra hosts` (without `--connection` and `--ansible-inventory`).

I've not tested my solution, but this should work. Ask me if you have issues

**Comment by FlxPeters** [comment]
Wow, thats great. Thanks a lot!

**Comment by philpep** [comment]
Without touching your tests files this is equivalent to:

`testinfra --hosts 'ansible://?ansible_inventory=databases/inventory.ini,ansible://?ansible_inventory=webservers/ansible.ini' hosts`

**Comment by FlxPeters** [comment]
Thx for the hint. is this a Ansible feature or a Testinfra feature?

**Comment by philpep** [comment]
This is a testinfra feature.
