### ISSUE TITLE
cannot get ansible backend running

### ISSUE THREAD

**Issue by clyso** [philpep/testinfra#72]
Hi,

trying to run a simple test via ansible:
testinfra --connection=ansible --ansible-inventory=/etc/ansible/hosts --hosts=test -v pakete.py
if run locally it works.
if run via ansible I always get following error:
RuntimeError: host unreachable: {'msg': u'SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh', 'unreachable': True, 'changed': False}
if i try to run ansible on this host i get no error:
ansible test -m ping
XXXX | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /etc/ansible/roles/

This is py.test version 2.5.1, imported from /usr/lib/python2.7/dist-packages/pytest.pyc
setuptools registered plugins:
  testinfra-1.0.2 at /usr/local/lib/python2.7/dist-packages/testinfra/plugin.pyc

Thanks :-)

**Comment by philpep** [comment]
Hi, can you paste your ansible.cfg and inventory ?

**Comment by clyso** [comment]
Hi,

ansible.cfg (only differences from default):
[defaults]
inventory      = /etc/ansible/hosts
gathering = explicit
host_key_checking = False
remote_user = orc
private_key_file = /root/orc_rsa
retry_files_enabled = False
[privilege_escalation]
become_ask_pass=True
[ssh_connection]
pipelining = True

inventory:
[test]
pod1-bl1.system.rot.hybris.com

in the mean time it set up an ansible with version 1.9.4 - works without problems
so it looks like thats a problem with version 2 of ansible

**Comment by philpep** [comment]
Hi, did you resolve your issue ? I cannot reproduce it, I think something is wrong in your setup but the relevant error message is hidden somewhere. If you feel enough confident with python you can debug the ansible code in `testinfra/utils/ansible_runner.py`. Also calling testinfra with `-vvs` will output more informations about what testinfra is doing.

**Comment by clyso** [comment]
Hi, i resolved the issue by downgrading the ansible version to 1.9
unfortunately i do not have version 2 running any more so i do not have the possibility to debug. sorry.

**Comment by clyso** [comment]
was eager to test again. upgraded ansible to v2.0.1.0. kept the old configs and tried to run testinfra - no problems. so looks like my old setup was wrong. sorry for the inconvinience and thank you for the help.
