### ISSUE TITLE
Is there a way to say if this test fails, then run this series of test?

### ISSUE THREAD

**Issue by emayssat-ms** [philpep/testinfra#81]
I am using testinfra extensively.
This is an awesome tool also for debugging.

Now I am deploying in europe while my desktop is in the california (west USA).
I am interested in using testinfra for support (i.e. quickly find out what the issue is)
But there is significant latency between EU and US, so if you run a lot of tests, it is going to take a lot of time.

I already use the multi-process testinfra (i.e. pytest-xdist, or testinfra -n 5), which somewhat address that issue. To go even further, I would like to disable/enable tests based on the result of others.
Is this possible?

The idea is to run only a small set of tests, if one fails, I run another series of test to troubleshoot even further the issue. That would be a killer feature if not implemented yet!

Best,

**Comment by philpep** [comment]
Hello, I've already done this kind of trick by using an autouse fixture that can disable all test from the same file:

```python
import pytest

@pytest.fixture(scope="module", autouse=True)
def _check_stuff(Command):
    if not Command("should i run these tests").rc == 0:
        pytest.skip()

def test_stuff(File):
    # [...]

```

**Comment by philpep** [comment]
I close this issue (pytest scope).
