### ISSUE TITLE
variables in tests

### ISSUE THREAD

**Issue by retr0h** [philpep/testinfra#82]
Is there a way to access ansible inventory inside the test itself?

I am putting together a set of tests that run across multiple environments.  I would like some of the tests to be explicit about the domain or URL it is testing.  This information is stored in ansible's inventory.  The test below feels wrong (`hostname -d`).

```
@pytest.mark.parametrize('host, scheme', [('api.pub.{}', 'https'), ('api.loc1.{}', 'http'),
])
def test_keystone_service_list(Command, host, scheme):
    domain = Command('hostname -d').stdout
    cmd = openstack('service list',
    password='keystone_admin_password',
    auth_host=host.format(domain),
    auth_host_scheme=scheme)
    out = Command.check_output(cmd)

    assert re.search(r'image', out)
```

Ideally, I'd like to run this same test across multiple environments, swapping out the inventory.

```
@pytest.mark.parametrize('host, scheme', [
    ('api.pub.{}.format(VAR_FROM_INVENTORY)', 'https'),
    ('api.loc1.{}.format(VAR_FROM_INVENTORY)', 'http'),
])
...
```

**Comment by philpep** [comment]
Hello,

Maybe you could use the `Ansible` module to get the value:

```
def test(Ansible):
    myvar = Ansible("debug", "msg={{ myvar }}")["msg"]
```

This is a bit dirty but should work for simple string variables. Let me known if you find a better way to do it, if not it could be interesting to provide a module to do it through the ansible python API.

**Comment by retr0h** [comment]
Yeah, I'm not sure this is going to work the way I expect it to work.  I'll give you a little more feedback as to what I am doing.

Variables exposed to testinfra should be the same variables that ansible converged against.  In our case we have a [custom vars plugin very similar to ursula's](https://github.com/blueboxgroup/ursula/blob/master/plugins/vars/default_vars.py).  The only difference it loads defaults from a directory.

When we converge ansible, we converge ansible with the following env vars, which basically allows ansible to merge the current inventory with a set of defaults.

```
    ANSIBLE_VAR_DEFAULTS_GLOB: ../../../inventory/fusion/metapod/defaults/*.yml
    ANSIBLE_VARS_PLUGINS: ../../../plugins/vars
```

If testinfra were to expose ansible vars inside the tests, it would need to load the vars the same way ansible loaded them.  However, if we were to have this functionality, I could really leverage testinfra against multiple deployed environments, and generisize my tests quite a bit.

**Comment by philpep** [comment]
Not sure to really understand what you're doing, but did you try to call testinfra with the same env vars that you run ansible (ANSIBLE_VAR_DEFAULTS_GLOB and ANSIBLE_VARS_PLUGINS) ? Testinfra use ansible API, so it must behave like ansible does.

**Comment by retr0h** [comment]
Ok, I will give that a try.

**Comment by retr0h** [comment]
I receive the following error when trying to utilize this type of a test.

Adding the following to a working test.

```
myvar = Ansible("debug", "msg={{ etc_hosts_primary_interface }}")
```

```
[jodewey:~/git/ansible-systems/roles/cisco.etc_hosts] [venv] correct-etc-hosts-test(+5/-1) 1 ± pip freeze | grep testinfra
testinfra==1.1.1
```

```
    def run(self, host, module_name, module_args=None, **kwargs):
        kwargs = kwargs.copy()
        if self.host_list is not None:
            kwargs["host_list"] = self.host_list
        if module_args is not None:
            kwargs["module_args"] = module_args
        return ansible.runner.Runner(
            pattern=host,
            module_name=module_name,
>           **kwargs).run()["contacted"][host]
E       KeyError: 'etc-hosts-02.example.com'
```

```
[jodewey:~/git/ansible-systems/roles/cisco.etc_hosts] [venv] correct-etc-hosts-test(+5/-1) 1 ± cat .molecule/ansible_inventory
etc-hosts-01.example.com ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/jodewey/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant
etc-hosts-02.example.com ansible_ssh_host=127.0.0.1 ansible_ssh_port=2200 ansible_ssh_private_key_file=/Users/jodewey/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant

[aio]
etc-hosts-01.example.com
etc-hosts-02.example.com
```

**Comment by philpep** [comment]
I gess you use ansible 1 ? I think the real error is "undefined variable" here (you should check what `Runner.run()` returns. I opened #83 to adress this bug.

**Comment by retr0h** [comment]
Yeah, still using 1.9.4, since 2 still has various issues IMO.

I am able to access variables which are defined in the file referenced by --ansible-inventory. However, I am unable to reference normal ansible inventory such as anything gathered by facts or role defaults defaults/main.yml.

[jodewey:~/git/ansible-systems/roles/etc_hosts] [venv] correct-etc-hosts-test(+8/-3) 1 ± cat .molecule/ansible_inventory
etc-hosts ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/jodewey/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant
etc-hosts ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_private_key_file=/Users/jodewey/.vagrant.d/insecure_private_key ansible_ssh_user=vagrant

[aio]
etc-hosts
etc-hosts

**Comment by retr0h** [comment]
Yes, using ansible 1.

To close out this thread, I am able to access inventory exactly as you described.  Verified it even handles my crazy use case, since it loads inventory just as ansible does.

It would be nice to have a more pythonic way to access the data.

**Comment by philpep** [comment]
Nice. Indeed having a helper to get variable (directly using ansible API) is a must have feature, I opened #85 to adress that.

I close this issue, feel free to re-open if you have new bug/feature to suggest ;)

**Comment by alop** [comment]
Following up on this issue. Today, I used `set_fact: foo=True` to define a variable in a task, then I tried to define a test for the value of 'foo' as such
```
@pytest.fixture
def check_foo(Ansible):
    hostvars = Ansible.get_variables()

    return hostvars['foo']
```
and was getting the same failures seen here, about `foo` being undefined.
Again, this is with ansible 1.9.6 and testinfra 1.4.2 and also testinfra 1.4.3.dev10

**Comment by philpep** [comment]
@alop testinfra doesn't have the knowledge of yours playbooks, hence this cannot work.
