### ISSUE TITLE
Adding new modules

### ISSUE THREAD

**Issue by blarghmatey** [philpep/testinfra#84]
What is the level of interest for receiving pull requests to introduce new modules? For instance I have written a couple of modules for verifying Python and Ruby modules (e.g. `is_installed` and version checking), and I am wondering if it would be desirable to include these directly in TestInfra or if they would be better served in an extension package?

**Comment by philpep** [comment]
Hi,

I'm open to modules that I can understand, test and maintain and that give the user a useful and unrestricted API (ie more than a oneliner that handle only a few cases).

I think handling python and ruby modules is a high interest for users of testinfra and I'll be happy to review your code (In this case, unrestricted API means virtualenvs handling ;) )
