### ISSUE TITLE
Get variables from ansible

### ISSUE THREAD

**Issue by philpep** [philpep/testinfra#85]
I'll be great to have a helper to read ansible variables.

I suggest:

```
>>> Ansible.get("myvar")
[{'my': 'complex'}, {'value': True}]
```

Also add a note on the docs to explain that testinfra loads ansible variable like ansible does (using the  python API). The relevant environment variable that alter ansible variable loading (vars plugins) must be set when calling testinfra.

**Comment by retr0h** [comment]
@philpep did you ever get around to implementing this?  I like the cleaner syntax to access vars vs `myvar = Ansible("debug", "msg={{ name_of_var }}")`.

**Comment by philpep** [comment]
@retr0h this should work with [Ansible.get_variables()](http://testinfra.readthedocs.io/en/latest/modules.html#testinfra.modules.ansible.Ansible.get_variables)

IIRC, there has been some issues in the past depending on the ansible version and vault encrypted variables. Let me know if it doesn't work for your use case.

**Comment by gohierf** [comment]
@philpep, I can't get Ansible.get_variables() to work while using Molecule.
I'm using :
ansible 2.4.1.0
molecule 1.25.0
testinfra 1.9.0

Here is an extract of the code I try to run :
```python
import testinfra.utils.ansible_runner

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    '.molecule/ansible_inventory').get_hosts('all')


def test_default(Ansible):
    vars = Ansible.get_variables()
    assert False
```

I get the following error when running `molecule test`:
```
_________ test_default[docker://iee-ans-role-vm-shared-folder-default] _________

Ansible = <ansible>

    def test_default(Ansible):
>       vars = Ansible.get_variables()

tests/test_default.py:8:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/site-packages/testinfra/modules/ansible.py:84: in get_variables
    return self._host.backend.get_variables()
/usr/lib/python2.7/site-packages/testinfra/backend/base.py:247: in __getattr__
    module = getattr(self._host, testinfra.utils.un_camel_case(name))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <testinfra.host.Host object at 0x2659bd0>, name = 'get_variables'

    def __getattr__(self, name):
>       assert name in testinfra.modules.modules, name + " is not a module"
E       AssertionError: get_variables is not a module

/usr/lib/python2.7/site-packages/testinfra/host.py:89: AssertionError
```

I hope that's not a too dump question but I can't find a way to get it to work.
Any idea on what's wrong ?

Also do you know of any extended documentation about using testinfra from molecule ?

**Comment by philpep** [comment]
Hi @gohierf does this work for you ?
```python
def test_default(host):
    vars = host.ansible.get_variables()
```

If it's works, it's a backward compat bug.

**Comment by gohierf** [comment]
Hi @philpep, thanks for the quick answer !
Actually I had tried that too but it hadn't pan out.
I get the same error:
```
_________ test_default[docker://iee-ans-role-vm-shared-folder-default] _________

host = <testinfra.host.Host object at 0x377bad0>

    def test_default(host):
>       vars = host.ansible.get_variables()

tests/test_default.py:8:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/site-packages/testinfra/modules/ansible.py:84: in get_variables
    return self._host.backend.get_variables()
/usr/lib/python2.7/site-packages/testinfra/backend/base.py:247: in __getattr__
    module = getattr(self._host, testinfra.utils.un_camel_case(name))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <testinfra.host.Host object at 0x377bad0>, name = 'get_variables'

    def __getattr__(self, name):
>       assert name in testinfra.modules.modules, name + " is not a module"
E       AssertionError: get_variables is not a module

/usr/lib/python2.7/site-packages/testinfra/host.py:89: AssertionError
```

**Comment by philpep** [comment]
Ok, that's because you're using the docker connection backend instead ansible.

ansible module only work when connecting to remote host through ansible: http://testinfra.readthedocs.io/en/latest/modules.html#ansible

The error message is definitively wrong, I open #288 for this

I don't know if molecule allow to use the ansible connection backend instead of docker when running test, but surely @retr0h has some hints ?

**Comment by retr0h** [comment]
Molecule v2 uses Ansible connection backend.

```/Users/jodewey/.pyenv/versions/molecule2-env-2.7.13/bin/py.test --debug --connection=ansible --ansible-inventory=/Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/.molecule/ansible_inventory.yml /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/tests/test_default.py```

**Comment by gohierf** [comment]
Alright, thanks for the fast feedback.
I guess I will have to use molecule v2 at some point.
