### ISSUE TITLE
test for file is_mounted

### ISSUE THREAD

**Issue by georgealton** [philpep/testinfra#89]
interested in adding an addition to the File module for testing if a path is mounted - wondering this should be implemented. 

I originally assumed that it would use `os.path.ismount()`, however other File tests are implemented using system binaries - there is a [mountpoint](http://linux.die.net/man/1/mountpoint) binary that could be used which fits into the style, but I'm not sure how common this is.

**Comment by philpep** [comment]
Yes testinfra use system binaries for remote execution. What's your usecase for this enhancement ? I wonder if a complete module to test mount points (and options) could be useful.

**Comment by georgealton** [comment]
my particular use case is around ensuring that after a server is provisioned that the gluster mounts that should have been configured in the provisioning stage are available

**Comment by jcftang** [comment]
+1 for I would be interested in testing network based mount points as well

**Comment by georgealton** [comment]
I've started something [here](https://github.com/georgealton/testinfra/blob/mount_module/testinfra/modules/mountpoint.py) - is this the right direction ?
