### ISSUE TITLE
Clarification on how to run tests

### ISSUE THREAD

**Issue by martinb3** [philpep/testinfra#91]
Hello! I'm looking for some clarification on what ways are supported for actually running tests. Do you anticipate most users to write pytest tests (run them with `py.test`) or use the testinfra command? Is one preferred over the other? Thanks in advance!

**Comment by philpep** [comment]
Hi, in most cases testinfra command is equivalent to py.test except when using `--nagios` option (which wrap py.test to produce a nagios compatible output), that's why the testinfra command exists (for now).

**Comment by martinb3** [comment]
Great, thanks!
